### ISSUE TITLE
Format of FASTQ

### ISSUE THREAD

**Issue by fungs** [bioboxes/rfc#10]
Which format should FASTQ files be in. I know there are at least some ways to allow for line breaks or not (the latter is more restricted and easier to parse). There should be a reference to every file format definition. If there is no stable definition on the web, we might have to provide it...

Should CONT_PAIRED_FASTQ_FILE/CONT_PAIRED_FASTQ_FILE/CONT_PAIRED_FASTQ_FILE_LISTING contain the path to a single interleaved FASTQ file or to a forward and reverse file? Again, I would put a link to a definition.

Johannes

**Comment by fungs** [comment]
I'm adding this for completeness which covers the definition of the FASTQ format:
doi://10.1093/nar/gkp1137

**Comment by michaelbarton** [comment]
That paper is included in the description of the FASTQ format - https://github.com/bioboxes/rfc/blob/master/data-format/sequence.mkd#description
