### ISSUE TITLE
Present at Computational Biology & Docker Conference London Sept 2015

### ISSUE THREAD

**Issue by avilella** [bioboxes/rfc#100]
From @snewhouse:

Computational Biology & Docker Conference to be held here in London Sept 2015, which will be open to the world of Docker enthusiasts. 

We hope to gather a decent group of us together to share ideas and start formalising this type of resource (looks like bioboxes is already moving that way...which is great!).

Please take some time to fill in our form to register interest at: http://core.brc.iop.kcl.ac.uk/events/compbio-docker-symposium-2015/

**Comment by Leprevost** [comment]
Hey sorry for the long time away, I'm still settling in here in EUA, there still a lot to do.

Anyway, I got an invitation to participate this meeting, but I'm not sure I can handle another long trip in the next months, maybe one of you guys in Europe can attend it. I can pass the contact of the person who invited me.

**Comment by michaelbarton** [comment]
@afolarin has kindly invited me to attend and discuss bioboxes at this
conference. Assuming that the JGI will allow me to travel, I will present what
we have done so far.
