### ISSUE TITLE
The input file schemas should be part of the RFC

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#103]
Biobox authors will need to download the input file schema for different types
of bioboxes. E.g. A short read assembler author will need to download the
schema of the same type and use it to validate the input data. I think we
should version the schema along side the RFC for the time being and then
provide a link to it.

**Comment by pbelmann** [comment]
I agree. We should create a 'schema' directory and link the schema files from the corresponding rfc document.

**Comment by pbelmann** [comment]
The schema is now in the same directory as the specification as you can see here:
https://github.com/bioboxes/rfc/tree/master/container/short-read-assembler
What we need now is a link to it from the specification then we can close this issue.

We should follow this pattern in every future bioboxes versions.
