### ISSUE TITLE
How can different versions of bioboxes be managed?

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#104]
There will be multiple versions of different bioboxes as authors update their
Docker images. We will need a way to manage this so that results can be
reproduced and shared. This was discussed in biweekly meeting #89. A few
options considered are:

  * Use the DockerHub image tags. For example the DockerHub java image
    maintains Java versions 6,7,8.

  * Use the build hash. Each build has a unique hash and this can be used to
    point to a specific version.

**Comment by bgruening** [comment]
+1 for image tags. The question is if the tag should include some indication of a particular biobox rfc/version.

**Comment by pbelmann** [comment]
+1 for image tags. @bgruening I think we should somehow include the biobox rfc version:

### Proposal: 
--
Since semantic versioning supports metadata, we could specify that a tag always looks like: 

`X.Y.Z-x.y`

X,Y and Z are the version for the application and the x,y refers to the rfc version.

##### Example:

`0.0.1-0.9`   0.0.1 is the application version and 0.9 is the rfc version. 



What do you think?

**Comment by bgruening** [comment]
I'm a big fan of readability, so maybe we should include bx (for biobox version/rfc) into the schema?

`bowtie:2.1.0-bx0.9`? This would also have the advantage of recognizing the `bx` as a separator. Version numbers can be really awkward and can contain dashes.

**Comment by pbelmann** [comment]
I agree:
 
`X.Y.Z-bxA.B` 
where
* X.Y.Z is the application version
* A.B is the rfc version
* bx is the delimiter

**Comment by michaelbarton** [comment]
Is this referring to dockerhub image tags? If so would it be better to have
tags in the format `X.Y-bxA.B`? I think that having a tag for each patch
bump could lead to a larger number of tags. For most users I don't think
they will want to distinguish between patch versions either (assuming that
we follow semantic versioning).

**Comment by michaelbarton** [comment]
Also would might we also use bbx instead of bx since we are placing files
in `/bbx` in the containers?

**Comment by bgruening** [comment]
@michaelbarton I think X.Y vs. X.Y.Z is really up to the developer who should know best the underlying software. The dev should bump the version (e.g. create a new tag) if the underlying software changes the results.

No objections against `bbx` or anything similar.

**Comment by avilella** [comment]
I like the system, it's similar to the wait ubuntu re-packages debian debs:

http://www.ducea.com/2006/06/17/ubuntu-package-version-naming-explanation/

Basically each package will be in the form: “*package-*X*ubuntu*Y****”.
Let’s break this apart and see what each part means:

   1.

   *package* = this is the name of the program/library.
   2.

   *X* = this is the debian version of the package
   3.

   if *X=0* this means that there is no debian package (or that the ubuntu
   team has forked a debian package to a newer version than the one found in
   the debian repositories) _ ex: bzip2-1.0.3-0ubuntu2_ (as shown in this
   example the debian package might be updated in the meantime and the ubuntu
   package will probably merged with it on the next version)
   1. *ubuntu*Y**** = this is the *Yth ubuntu* version of the debian
      package.
   4. if this is *missing *this mean that it is a clean, unchanged debian
   package *ex: gzip-1.3.5-12* (in this sample, this is the original debian
   package included in ubuntu)
   5. if this is *present *it means that Ubuntu has taken the debian
   package and released it with some additional patches or bug fixes. _ ex:
   sudo-1.6.8p12-1ubuntu6_ (in this sample this is the 6th version of the
   ubuntu package based on the debian version 1.6.8p12-1 of sudo).

As a conclusion, the version of a package can be: *2.6.0-1* – means that
this is the 1st debian package of version 2.6.0. No ubuntu changes were
included. *2.6.0-1**ubuntu1* – means that this is the 1st ubuntu package
based on the debian package version 2.6.0-1 *2.6.0-0**ubuntu1* – means that
there was not a debian package yet and this is the 1st ubuntu version of
package 2.6.0

**Comment by bgruening** [comment]
Exactly learn from the big onces :)

**Comment by michaelbarton** [comment]
>  I think X.Y vs. X.Y.Z is really up to the developer who should know best
>  the underlying software. The dev should bump the version (e.g. create a
>  new tag) if the underlying software changes the results.

@pbelmann suggested [semantic versioning](http://semver.org) which I agree
with. In semantic versioning each field has a specific meaning. The Z field
is "backwards-compatible bug fixes.". Using docker with the above
convention my suggestion is that a user would do something as follows:

```
docker pull bioboxes/soap:1.9-bbx0.1 
```

This would always fetch the minor/major version with the latest bug fixes
without having to specify the patch version.

**Comment by michaelbarton** [comment]
We may be able to just use the new digest syntax also - https://github.com/docker/docker/pull/11109

**Comment by michaelbarton** [comment]
Or specify a label inside the dockerfile - http://rancher.com/docker-labels/

**Comment by pbelmann** [comment]
The last point to discuss in this issue is whether we include the patch version number or not:

**Pro**
* As a developer I would always like to specify in the tag when I have for example fixed a bug.

**Con**
* As a user it might be annoying to specify a tag for every tiny patch the developer could provide.

Since one of the initial ideas behind Bioboxes is to build software that should be easy to use, I agree with @michaelbarton to skip the patch version and to use the following syntax:

`X.Y-bbxA.B`
where

   * X.Y is the application version
   * A.B is the rfc version
   * bbx is the delimiter

 I don't see a reason for using the digest syntax or the dockerfile label. In my opinion a tag should be sufficient.

So I think this issue should be closed when all existing bioboxes are available on docker hub with the above version tag syntax.

**Comment by michaelbarton** [comment]
@pbelmann I agree. Let's go ahead and start labelling the biobox docker images
this way as we create them.

**Comment by michaelbarton** [comment]
Unless there are futher additions I will close this issue as resolved.

**Comment by pbelmann** [comment]
ok. but I need write permissions to the dockerhub repository.

**Comment by michaelbarton** [comment]
I have added you to the dockerhub repo
