### ISSUE TITLE
Biweekly review meeting - Thu Apr 09 15:30 GMT

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#105]
This issue is for the next biweekly review meeting. Please add any related
comments here. I will create a google hangout a few minutes beforehand and post
it.

**Comment by fungs** [comment]
I'm on vacation this whole week, so I won't attend today's meeting.

**Comment by pbelmann** [comment]
This time I just have time till 16:00 GMT.

**Comment by avilella** [comment]
Minutes
----------------------------------------

Attending: @pbelmann and @avilella

- We used the velvet biobox as an example to go step-by-step to:

1. create a biobox using the https://github.com/bioboxes/velvet/blob/master/Dockerfile as a template

2. How to define the input for the job via the input `biobox.yaml` (http://bioboxes.org/getting-started)

3. Execute docker run pointing to the `input_data/` folder, and obtain the output files and the output `biobox.yaml`

So right now, after the explanation, someone like @avilella who hasn't been closely involved in all the steps, managed to get a clear picture of how the system works, and would be able to give it a try to create biobox container n+1 .

AOB: @avilella mentioned that the input `biobox.yaml` would be roughly equivalent to the needed `job.json` in the common-workflow-language parlance:

https://github.com/common-workflow-language/common-workflow-language/blob/master/examples/draft-2/bwa-mem-job.json

@tetron , any comments on the bioboxes velvet example and how it would play with CWL?

**Comment by michaelbarton** [comment]
I think there's some confusion about the time. I assumed the meeting starts
now. I think this is because the clocks have changed and now the UK is on
BST. I'll set up the next meeting to make the international time clearer.

**Comment by tetron** [comment]
@avilella thanks for the heads up, I will take a look.

**Comment by michaelbarton** [comment]
Next meeting scheduled in #122
