### ISSUE TITLE
oswitch and bioboxes

### ISSUE THREAD

**Issue by avilella** [bioboxes/rfc#106]
Copying from @yeban email:

I think Bioboxes is a very commendable effort, and the community can potentially benefit a lot from it. [...] If all goes as planned oswitch will be deployed on EOS cloud (on NERC's JASMIN cluster) this week [...]

Perhaps oswitch could implement bioboxes rfc so that the boxes we build can be trivially run using oswitch. For example, mounting input files to the correct location within soap image (https://github.com/bioboxes/soap). We have homebrew and Ubuntu/Debian package already for easy installation.

Details:

https://github.com/yeban/oswitch

```
mymacbook:~/2015-02-01-myproject> oswitch bioboxes-soap-123
    ###### You are now running: bioboxes-soap in container bioboxes-soap-123-7187. ######
```

**Comment by michaelbarton** [comment]
I will close this issue as inactive. @yeban we would like to hear any feedback
you have if you have tried using the bioboxes spec already.
