### ISSUE TITLE
EDAM ontology for descriving data formats

### ISSUE THREAD

**Issue by bgruening** [bioboxes/rfc#107]
bioboxes should evaluate the usage of [EDAM ontology](http://edamontology.org) to describe file/data formats.

**Comment by michaelbarton** [comment]
Thank you for the suggestion Bjorn. We have discussed EDAM in #90 and #95
but have not arrived on a concrete solution. Could you suggest an example
of this might be managed?

**Comment by michaelbarton** [comment]
I will close this issue as inactive.
