### ISSUE TITLE
Create page for with an example of getting started with bioboxes

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#108]
As I user who is unfamiliar with bioboxes I should be able to go to a page on
bioboxes.org and get an understanding of how bioboxes work and can be used.
This page should contain an example of running a simple biobox.

**Comment by michaelbarton** [comment]
I have [created a branch][branch] on the bioboxes.org website. This includes a
[short tutorial page][tutorial] on how to get started with bioboxes.

@pbelmann I mention in the tutorial using a bioboxes/velvet container. We don't
have this yet however this reference implementation of the short read assembler
is almost there. I didn't include the soap biobox as I believe this needs the
fragment size in the biobox.yml, correct? I thought that a first introduction
to bioboxes should be as simple as possible.

What do you think?

[branch]: https://github.com/bioboxes/bioboxes.org/tree/feature/getting-started
[tutorial]: https://github.com/bioboxes/bioboxes.org/blob/feature/getting-started/source/getting-started.mkd

**Comment by pbelmann** [comment]
Yes, for soap you need the fragment size.  The branch looks good Michael. But we should decide whether we use .yaml or .yml. I think [.yaml](http://www.yaml.org/faq.html) is the official one.

**Comment by michaelbarton** [comment]
>  But we should decide whether we use .yaml or .yml. I think .yaml is the
>  official one.

You're right, we should be consistent. I'll change this to include .yaml
and add a test in the website for this.

**Comment by michaelbarton** [comment]
There's now a page for getting started with bioboxes -
http://bioboxes.org/getting-started/
