### ISSUE TITLE
New binning container spec

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#110]
We need a new binning specification that works similar to the [new assembler spec 0.9.0](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd) with yaml input and output definitions.

Important Issues that are connected to this issue are:

* Database section. Binning tools are using databases, so we need a solution for specifying a database and mounting them to a container. The problem here is that there are many different databases that could be used and the directory structure of a database might change.  #69  

* Validation container similar to the new assembler spec validator. #84 

This issue should be closed when #69 and #84 are solved and a new binning container spec is merged.

**Comment by pbelmann** [comment]
In PR #136 I added the new binning spec.
I have one simple [validator](https://github.com/pbelmann/validator-binning) for binning that must be moved to the bioboxes repository and two working examples:

* [kraken](https://github.com/pbelmann/kraken) 

* [metaBAT](https://github.com/pbelmann/metaBAT)

Features:

* [databases](https://github.com/pbelmann/rfc/blob/feature/new_binning_spec/container/binning/binning.mkd#databases-definition) can be specified in yaml (refseq, blastdb, ncbi_taxonomy, ncbi_genomes, cog)

* In the new binning spec I introduced the [cache](https://github.com/pbelmann/rfc/blob/feature/new_binning_spec/container/binning/binning.mkd#cache-definition) parameter. 
  Scenario:
  If a tool uses for example a custom database that is not following the spec it can download the database to the writeable "cache" directory. On the second run it could reuse the database without downloading it again.

Further notes:

* It is obvious that binning bioboxes will be interchangeable just to a certain degree. If one tool specifies in the yaml the refseq database and another one uses blastdb, you can not simply reuse the yaml.
  But I think when we continue to work on bioboxes we can improve the usability.
  For example it would be nice if a biobox could simply return the yaml types it needs, like a signature.    

* The validator does not offer the database type for testing. And can not be used by tools that need a database. This is why we have to think about creating a bioboxes service (probably with jenkins)
that runs on a machine with multiple databases. That way the developer could register his github repositories and on every git push the tests will be rerun. 

**What do you think?**
@fungs since the profiling spec is nearly the same I could prepare a PR for profiling too.

**Comment by michaelbarton** [comment]
This looks like a sensible way of managing the requirements for large databases.
