### ISSUE TITLE
Megahit Assembler Biobox

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#112]
The [megahit assembler](https://github.com/voutcn/megahit) should be available as a biobox and implement the assembler interface [0.9](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd).
It is recommended to use an existing Dockerfile like [linuxbrew](https://github.com/sjackman/docker-bio/blob/master/assemblers/Dockerfile) or [nucleotid.es](https://github.com/nucleotides/docker-megahit).
Please see at [bioboxes.org](http://bioboxes.org/how-to-create-a-biobox/) for a step by step description for creating a biobox and comment on this issue or issue #99 if the interface makes an implementation impossible.

**Comment by staynerzone** [comment]
Done!

You can find the actual Megahit-Biobox at
https://github.com/staynerzone/megahit

Greetings

**Comment by pbelmann** [comment]
thanks @staynerzone . I take a look at it.

**Comment by pbelmann** [comment]
thanks @staynerzone  I created a fork of your megahit repo:
https://github.com/bioboxes/megahit
