### ISSUE TITLE
SGA Assembler Biobox

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#113]
The [sga assembler](https://github.com/jts/sga) should be available as a biobox and implement the assembler interface [0.9](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd).
It is recommended to use an existing Dockerfile like [linuxbrew](https://github.com/sjackman/docker-bio/blob/master/assemblers/Dockerfile) or [nucleotid.es](https://github.com/nucleotides/docker-sga).
Please see at [bioboxes.org](http://bioboxes.org/how-to-create-a-biobox/) for a step by step description for creating a biobox and comment on this issue or issue #99 if the interface makes an implementation impossible.

**Comment by mlyod** [comment]
Everything done  ->   (https://github.com/mlyod/sga_biobox)

**Comment by pbelmann** [comment]
@mlyod  I created a PR.

**Comment by pbelmann** [comment]
thanks @mlyod
