### ISSUE TITLE
IDBA Assembler Biobox

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#115]
The [IDBA assembler](http://www.ncbi.nlm.nih.gov/pubmed/22495754) should be available as a biobox and implement the assembler interface [0.9](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd).
It is recommended to use an existing Dockerfile like [linuxbrew](https://github.com/sjackman/docker-bio/blob/master/assemblers/Dockerfile) or [nucleotid.es](https://github.com/nucleotides/docker-idba).
Please see at [bioboxes.org](http://bioboxes.org/how-to-create-a-biobox/) for a step by step description for creating a biobox and comment on this issue or issue #99 if the interface makes an implementation impossible.

**Comment by MarkUgarov** [comment]
One Solution: https://github.com/MarkUgarov/idbadebian

**Comment by pbelmann** [comment]
thx @MarkUgarov
