### ISSUE TITLE
Sparse Assembler Biobox

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#116]
The [Sparse assembler](https://sites.google.com/site/sparseassembler/) should be available as a biobox and implement the assembler interface [0.9](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd).
It is recommended to use an existing Dockerfile like [linuxbrew](https://github.com/sjackman/docker-bio/blob/master/assemblers/Dockerfile) or [nucleotid.es](https://github.com/nucleotides/docker-sparse-assembler).
Please see at [bioboxes.org](http://bioboxes.org/how-to-create-a-biobox/) for a step by step description for creating a biobox and comment on this issue or issue #99 if the interface makes an implementation impossible.

**Comment by maximseitz** [comment]
Everything done, take a look please. 
https://github.com/maximseitz/sparse_biobox

**Comment by pbelmann** [comment]
@maximseitz Thanks a bunch
