### ISSUE TITLE
The biobox validator should be simple to use for developers

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#120]
At present the biobox validator is difficult to use and test. This is due to
the requirement of running a Docker daemon inside another Docker container.
Using Docker-in-Docker requires the `--privileged` flag which may be
unacceptable to many users because this allows escalated access by third-party
containers. Continuous integration testing of a biobox using the validator will
also be difficult because services like circleci or shippable do not allow the
use of the `--priviledged` flag either. This security issue is outlined in the
[Docker-in-Docker][dind] blog post.

    that there are serious security implications there: since the private
    Docker instances run in privileged mode, they can easily escalate to the
    host

[dind]: https://blog.docker.com/2013/09/docker-can-now-run-within-docker/

The validator works as a combination of commands which run a biobox with test
data. Therefore the validator needs to be able to contain evaluation scripts
and data to ensure the correct outputs. A Docker container is ideal because
everything can be bundled inside the container. An ideal situation would be
running without the `--privilege` flag to lessen these security issues. This
however looks unlikely in the near future based on jpetazzo/dind#60 and
jpetazzo/dind#43.

The validator should be simple to use for developers and also simple to set up
on a CI server. At present this is not the case in either situation - see
bioboxes/validator-short-read-assembler#7 and
bioboxes/validator-short-read-assembler#19. Therefore I believe the current
state of the validator should be reevaluated with respect to ease of use for
others. I think the priorities for the validator should be:

  * Available to use without escalated security privileges.
  * Available to use on a CI server such as shippable or circleci.
  * A simple CLI interface which makes it easy and straight-forward to use. The
    validator should help developers create a biobox rather than place
    additional burden.

**Comment by michaelbarton** [comment]
I experimented with running [rkt in Docker][rind]. Rkt is an alternative
container implementation that can also run Docker containers. If rkt could run
inside a Docker container without needing `--privilege` this solve the
escalated security issue. This however did not work, as rkt is not able to run
Docker containers inside a Docker container without the `--privileged` flag.

**Comment by michaelbarton** [comment]
I have also experimented with using [travelling ruby][tr]. This could allow the
validator to be bundled with its own ruby interpreter for either Linux or Mac
OSX platforms. This would mean the validator is provided as a tar file that
could be unarchived and then run with a bash wrapper script calling bundled
ruby. I was able to get a simple version working, however the cucumber library
does not work because it depends on the [gherkin library][] which must be
compiled for each system.

It could be possible to build our own version of this dependency as the [code
for building gems is available][code]. If this avenue of bundling a ruby
interpreter with all required gems works, then it would also be possible to
include the required data files too and then start a bash script with the image
name as an argument.

[gherkin]: https://github.com/cucumber/gherkin
[tr]: http://phusion.github.io/traveling-ruby/
[code]: https://github.com/phusion/traveling-ruby/blob/master/linux/build-ruby

**Comment by pbelmann** [comment]
What if we build a "Bioboxes CI Service" like a simple circle ci?

### Scenario

In my opinion it would be great if a developer could just register with his github account on a "Bioboxes CI Service" and register his github repository that contains a Dockerfile. On every push he makes "Bioboxes CI" would build the container and check with our tests if the container still follows the Bioboxes Interface. The "Bioboxes CI Service" would report back to the user with an Icon like [Travis](http://docs.travis-ci.com/user/status-images/) and circle ci are already using. It could even test the container against different bioboxes versions (0.8.0 - 0.9.0) and types (assembler, short-read-processor, binning, profiling)

### What we would need for this:

* [Jenkins](https://jenkins-ci.org/) for configurable and flexible continious integration
* We would have to take a look at the [github api](https://developer.github.com/libraries/) for the registration by using OAuth.

I have found a description for connecting jenkins and github http://www.therightcode.net/use-docker-jenkins-to-run-github-tests/ . 


@michaelbarton this would not solve all the points you have listed in your first comment but I think on the long term this would be a useful feature/service Bioboxes could offer.

**Comment by michaelbarton** [comment]
Could you take at look at PR - bioboxes/validator-short-read-assembler#24. I've
removed the Docker-in-Docker image and instead provide a tar.gz that contains
the feature and data files. The user runs the `validate` script, included in
the package, to validate an image. I've updated the documentation in the `doc`
folder with respect to this.

This doesn't preclude the use of DinD in addition to this `.tar.gz` package,
the package could be pulled into the bioboxes/validator-base image and used the
as previously. This would allow us the provide the validator in two different
methods. Importantly the validator can now be used on a CI server, and
currently works on circleci for bioboxes/velvet -
https://circleci.com/gh/bioboxes/validator-short-read-assembler/93

**Comment by michaelbarton** [comment]
Thanks for the suggestion Peter. I agree that this would be very useful for
users, they could register their image github repository and then get feedback
if they break. This would help us ensure the standard is maintained too. 

My initial concern is the `--privileged` flag required to run Docker-in-Docker
for testing. I think it could be possible to upload a malicious image to a
testing service which could breakout of Docker into the server with the
escalated privileges. I would worry about managing the security issues
associated with this.

**Comment by pbelmann** [comment]
I agree, we should not use the DinD until we find a better solution. 

I tried to use the new validator https://github.com/bioboxes/validator-short-read-assembler/pull/24 :

Problems:
1. Documentation: When I extracted the tar.gz, the created directory is "build" and not "validate-short-read-assembler".
2. Every test failed with velvet because the message is always:
```
docker: "run" requires a minimum of 1 argument. See 'docker run --help'.
``` 
I think the reason for this is that you are not setting the IMAGE and TASK variable in your validate script in current tar.gz on s3.

> My initial concern is the --privileged flag required to run Docker-in-Docker
> for testing. I think it could be possible to upload a malicious image to a
> testing service which could breakout of Docker into the server with the
> escalated privileges. I would worry about managing the security issues
> associated with this.

I see your point but if we could use your new validator we don't have use DinD and `--privileged`, right?

**Comment by michaelbarton** [comment]
Thanks for testing this Peter. Both of these should be fixed in the 0.1.1 release. Repeating the example in the doc works for me now. We may need to add a tag or version number to image in the documentation as an out-of-date bioboxes/velvet image will cause the example to fail. The feature tests for the validator now test the generated .tar.gz, so hopefully this will catch these types of errors in future.

**Comment by michaelbarton** [comment]
> I see your point but if we could use your new validator we don't have use DinD and --privileged, right?

Yes, that would work. We might also want to keep a list of biobox assemblers and post it on the bioboxes site. I'd be happy to move the nucleotid.es assembler list to bioboxes - http://nucleotid.es/assemblers/

**Comment by michaelbarton** [comment]
If the PR bioboxes/validator-short-read-assembler#24 looks good, this can be merged. This will automatically update the documentation on bioboxes.org.

**Comment by pbelmann** [comment]
:+1: I merged it.

I will give it a try next week with the bioboxes service.

Yes a list of bioboxes would be great!

I think this issue can be closed now.

**Comment by michaelbarton** [comment]
A few minor errors but the documentation is live now - http://bioboxes.org/validator/short-read-assembler/
