### ISSUE TITLE
The bioboxes website should have a consistent step-by-step guide for creating a biobox.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#123]
This guide should help developers create a biobox. The better and easier this guide is, the better adoption we may expect to have of bioboxes.

**Comment by pbelmann** [comment]
In PR bioboxes/bioboxes.org#32 I have added minor changes/fixes to the existing guide. I will add a PR with a better guide in the next days.

**Comment by pbelmann** [comment]
I PR bioboxes/bioboxes.org#34 I have added a developer guide by

* splitting up the steps in several pages
* connecting the pages with "previous" and "next" links
* extending the examples
* extending the rfc description
* exchanged the dind  with the ruby based validator 

I hope that it is easier now to understand how to build a biobox. 

What do you think?

**Comment by michaelbarton** [comment]
Thanks @pbemlann. This is great work I made a few edits and merged the PR. I
think this will be really helpful for developers. Perhaps @jfroula could take a
while he is developing his biobox.

**Comment by pbelmann** [comment]
In @asczyrba  seminar I received valuable feedback from the students:

Summary:

- [ ] All code examples should have a caption like "Dockerfile, Bash, ....."

- [ ] explain bash commands like (`set -o errexit` and `set -o nounset`)

- [ ] "Creating a docker image": Dockerfile example does not correspond to the velvet Dockerfile in the github repository.  (e.g missing a flag "--no-check-certificate")

- [ ] links to the next steps are missing (see #130)

- [ ] "Create a task" page: I would be nice if we could mention that a taskfile is placed inside the docker container with an ADD command and maybe show how it is executed (grep,...)

- [ ] We should state that you can add muliple tasks to the container and show another specific task beside the default task.

- [ ] Putting everything together: 
   - [ ] How are the scripts connected? Which file is the entrypoint? What is an entrypoint? 
   - [ ] Show the final Dockerfile with all integrated (added) scripts.
   - [ ] Explain where are the scripts added and especially **why**

**Comment by michaelbarton** [comment]
These are all useful points, I think we should include them because the
students on the course are the typical audience we might ask to create a
biobox. Improving the documentation should help adoption and use of bioboxes.

> "Creating a docker image": Dockerfile example does not correspond to the
> velvet Dockerfile in the github repository. (e.g missing a flag
> "--no-check-certificate")

This point makes me think that we may have a problem maintaining documentation
while the project is in flux and we are changing code and tools. For example if
we change how a specification, this may break the documentation if we forget to
update it. One solution to this would be to make each example a complete set of
working code. This would allow the code blocks to be pulled out of the HTML of
each guide page and run. This could be done on the CI server which report any
broken documentation pages. This could catch problems such as the one above.

**Comment by michaelbarton** [comment]
> "Creating a docker image": Dockerfile example does not correspond to the
> velvet Dockerfile in the github repository. (e.g missing a flag
> "--no-check-certificate")

Also in this specific case I think installing `ca-certificates` along with
`wget` solves this.

**Comment by pbelmann** [comment]
> This point makes me think that we may have a problem maintaining documentation
while the project is in flux and we are changing code and tools. For example if
we change how a specification, this may break the documentation if we forget to
update it. One solution to this would be to make each example a complete set of
working code. This would allow the code blocks to be pulled out of the HTML of
each guide page and run. This could be done on the CI server which report any
broken documentation pages. This could catch problems such as the one above.

I agree that we should find a solution for this.
In PR bioboxes/bioboxes.org#37 I have divided velvets code files in smaller parts and described each part. At the end of each section an entire/updated Dockerfile/script is available that the developer can try out. I think we could test them on circle ci. 

Another option would be to load external files in code blocks.
That way we just have to ensure that the velvet code in Github Repository works and load the files from the repository. 

I'm not sure which option is easier to achieve.

**Comment by michaelbarton** [comment]
I've created a PR which provides additional documentation on installing software in an image. Merge if this looks good - bioboxes/bioboxes.org#39

**Comment by michaelbarton** [comment]
I have created a specific issue for the problem of incorrect documentation.
Otherwise I believe the recent updates to the [developer guide][dg] resolve
this issue.

[dg]: http://bioboxes.org/guide/developer/
