### ISSUE TITLE
Biweekly review meeting - Thu May 7 15:00 UTC

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#127]
Germany    - 5.00 PM
UK         - 4.00 PM
California - 8.00 AM

[Google Hangout][GH]

[GH]: https://plus.google.com/hangouts/_/gq3q6tue52f4eslddlmqafeuhua

**Comment by michaelbarton** [comment]
I'm not able to create a hang out with my phone. Could someone else create one.

**Comment by fungs** [comment]
Sorry, it seems I can't join the call, it says I'm not in the organization.

**Comment by avilella** [comment]
trying now...

**Comment by avilella** [comment]
https://plus.google.com/hangouts/_/gvbsoinmgxbqe7fbeoikkpwbkma

**Comment by michaelbarton** [comment]
## Existing issues

  * #110 @pbelmann has updated the bioboxes binning container specification to
    match the current input/output formats. The PR #136 merges this into the
    RFC master branch.

  * #9 @michaelbarton mentioned that the json-schema could be generated from
    the biobox signature. This would mean all that is needed to validate the
    biobox.yml is the signature, instead of the schema.yml. @michaelbarton will
    update the issue with more details.

  * #126 The terms in the biobox signatures, such as FASTQ, are a restricted
    vocabulary which must be managed in a sensible way. We've mentioned EDAM in
    the past but this issue has not progressed. We may also need to create our
    own list of terms in the interim.

  * #86 @pbelmann mentioned that [Apache Avro][avro] maybe an improvement over
    json-schema as it could link to other schema. He may explore this as a
    possiblity.

  * #135 We discussed the issue of managing logs and other output that is not
    specific to the data being produced, e.g. contigs. We agreed on an optional
    mounted directory where these would be placed.

[avro]: https://avro.apache.org/

## New issues

  * We discussed the option of passing non-input specifications to the biobox.
    This would be details like number of CPUs or memory allocation. We agreed
    for the time being to use the docker client ability to specify these.

  * We discussed the possibility of using named arguments in the signatures.
    This would simplify the signatures and biobox.yml files as the arguments
    would not be based on their position in the argument list, but instead
    based on a key in an argument dictionary. We agree this is worth exploring
    but possibly at a later time after bioboxes is more stable.

    (@michaelbarton note: We have include a version number in the biobox.yaml
    file so it should be possible to change this in future and biobox authors
    can validate against the version number. The input validator already does
    this.)

  * #137 @pbelmann described that it is difficult to validate the binning
    biobox because it requires may require a large database to be provided. One
    possibility is to create our own service which validates the containers.

  * #139 @fungs described that it would be useful to override the defaults for
    where data is placed.

  * @pbelmann mentioned an evaluation container that would produce metrics from
    given input data. @michaelbarton said this would be useful at the JGI as
    they generate a lot of metrics from fastq data used for quality control.
    @pbelmann will post further details of this.

## Action items

These current action items for the next few weeks.

  * The assembly container spec appears to be stable. The @bioboxes/core-team
    feels confident that containers matching this spec can now be generated and
    used in @nucleotides and the @cami-challenge.

  * @pbelmann and @fungs will finalise the binning and profiling container RFC.

  * @michaelbarton will work on developing the pre-processing RFC.
