### ISSUE TITLE
The bioboxes website should have an about page

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#128]
There currently isn't one. People arriving at the site for the first time will
want to learn what the project is for.

**Comment by michaelbarton** [comment]
I created a PR bioboxes/bioboxes.org#31. Please let me know what you think.

**Comment by pbelmann** [comment]
looks good @michaelbarton .

Should we add a part of the manifesto to the front page so people can directly see the aim of bioboxes.

**Comment by michaelbarton** [comment]
What part of the manifesto should add? @afolarin you also mentioned that the
tag line of bioboxes could be clearer.

**Comment by michaelbarton** [comment]
Closed as inactive
