### ISSUE TITLE
How could the NGSeasy developers and the bioboxes developers collaborate?

### ISSUE THREAD

**Issue by snewhouse** [bioboxes/rfc#129]
Hi All

We've been in contact via emails - we'd really like to get involved and help shape the Docker + Bioinformatic tool evolution. 

We are interested in how we chain together Dockered tools for standard pipelines - so far we have been making quick and dirty solutions with simple bash scripts and having to build multi app images to help streamline pipes and data processing eg see https://github.com/KHP-Informatics/ngseasy#a-special-note-on-the-ngseasy-base-image

More soon

Steve

**Comment by michaelbarton** [comment]
Thanks for your interest @snewhouse. I would like us to work together bioboxes,
especially since you have experience with NGS and Docker already. This project
began as a collaboration between CAMI and nucleotid.es, and so the I think the
more that others can contribute the better.

My initial suggestion would be to try and create a biobox for one of the listed
issues e.g. #111. Building a biobox might give you an understanding of the
decisions we have made so far and allow you to suggest areas where improvements
could be made. Eventually, when we have the specs for bioboxes fleshed out, we
do want to start chaining them together to create workflows.

**Comment by afolarin** [comment]
@snewhouse @michaelbarton what's the impression on present stability of bbx as a standard?

If it makes sense, I'd be happy to building bbx containers for the trunk part of NGSeasy, I think we have much of the logic already worked out (albeit rough around the edges). 

I make the assumption that velvet example is the template to go for or is this likely to change based on #132. @ntijanic any feeling as to how well Biobox will play with CWL?

**Comment by ntijanic** [comment]
It looks like we'll just need to add the ability to choose output directory from cwl and they should be compatible (making any bbx usable in cwl workflows with little effort).

**Comment by michaelbarton** [comment]
> what's the impression on present stability of bbx as a standard?

The standard is currently in a state of some flux. As use the containers
we identify problems or areas where the spec is undefined. My personal
preference is not to publish this as a finalised standard until we expect
few changes. The worst situation would be identifying a major issue in
the standard and having to ask authors and developers to change all their
containers.

Having said that we do still need developers to create bioboxes and
test-drive the standard to provide feedback or improvements. @pbelmann
has been getting feedback from students developing biobox containers at
Bielefeld. We are also aiming to eventually put Docker and bioboxes into
production for our pipelines here at the JGI, which will should help to
iron out wrinkles.

> If it makes sense, I'd be happy to building bbx containers for the trunk
> part of NGSeasy, I think we have much of the logic already worked out
> (albeit rough around the edges).

I think this is a good idea. From looking at the NGSeasy README you
would need mapping, QC, preprocessing and assembly containers? Is this
correct?  We have a short read assembler spec, and a proposal for a
read-preprocessor (#77).

**Comment by snewhouse** [comment]
@michaelbarton @afolarin looking forward to the meet up on Monday 18th. 
@michaelbarton do you want to come to us down at Denmark Hill or shall we sort a central London location out?

**Comment by michaelbarton** [comment]
I will close this issue as inactive.
