### ISSUE TITLE
workflow management tools for biobox pipelines

### ISSUE THREAD

**Issue by afolarin** [bioboxes/rfc#133]
The typical bioinformatics usecase will be based around processing data through multiple containerized components (workflow/pipeline).

There seemingly are a never-ending supply of workflow management tools for orchestrating bioinformatics pipelines. Naturally, bioboxes should play nice with any system, but, given the nature of docker containers there are likely to be workflow management tools that work better for stringing together bioboxes.

Specifically around docker container workflows I'm aware of:
http://www.nextflow.io/docs/latest/docker.html
https://www.rabix.org/
https://github.com/CenturyLinkLabs/dray

I'm curious to know what thoughts the community have on this area. Is it something you feel has a strong bearing on the biobox spec?

**Comment by avilella** [comment]
I will give my 2c but this is by no means a complete description of what's
been happening so far:

There has been some talk about the difference between tools and workflows
with respect of bioboxes, and I would say that so far there isn't a strong
view towards limiting the definition of a biobox or containerised tool in
one way or another. Or to put it another way, there will be people that
will like to put several tools stringed together in a multi-step process,
all within a container. If they are inclined to put all that inside a
biobox container, that's ok. Other people will prefer having a separate
container for each separate step of the workflow. These can all co-exist in
the same ecosystem.

Now, that said, there is another group of people working with a bigger
focus on the workflow side of things, called CWL:
github.com/common-workflow-language

Rabix is a predecessor of some of the work happening nowadays in CWL, with
contributions from about 4-6 main developers.

We are trying to make sure that bioboxes and CWL are communicating each
other's efforts, and we try to attend each other's conf calls whenever we
can. At the moment, bioboxes is more focused on the efforts of
containerising tools, and then after than, making sure that CWL can consume
bioboxes containers within CWL's definition of jobs/tasks/workflows, or in
the current draft 2, commandlinetools/processes/workflows.

Another difference is that bioboxes is now heavily favouring using docker
containers, whereas CWL is more generic in the sense that a tool can be a
container, but can also be something else.

Hope it helps

**Comment by afolarin** [comment]
Yes, totally agree that people should not be shoehorned into some particular way of doing things -- that would inevitably be the wrong path. 

I've seen CWL and good to see you are in communication. 

I would however comment on the strapline for the bioboxes website http://bioboxes.org/  
`"a standard for creating interchangeable bioinformatics software containers"`
I do wonder how interchangeable multi-tooled containers will be, probably more of a design choice than anything. I like the idea of reuse of containers.

**Comment by snewhouse** [comment]
agree...but dont think this will be a "one-size-fits-all". The eco systems for workflow/pipelines will be very different from single-tool containers, and we should be thinking of both...looking forward to working this out with everyone.

**Comment by michaelbarton** [comment]
I will close this topic as inactive
