### ISSUE TITLE
YAML of assembler -- max_read_len arguments

### ISSUE THREAD

**Issue by voutcn** [bioboxes/rfc#134]
Some assemblers (MEGAHIT, SOAPdenovo etc.) require this. It's also useful for pipelines with pre-assembly steps (for example merging PE reads if read_len * 2 < insert_size).

**Comment by pbelmann** [comment]
Hi @voutcn,

please correct me if I'm wrong, but I think you can compute the maximum read length out of the fastq data.

I'm asking this because we want to create intefaces that are as simple as possible and therefore contain as less as possible parameters.

**Comment by voutcn** [comment]
Understand, thanks!
