### ISSUE TITLE
How should a biobox produce log data

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#135]
A biobox should output the log data of a containerized tool.

There are two options:

1. Use STDOUT/STDERR from the running container to place the data anywhere 

2. Use an additional, optional directory in the output folder with a log file in it.

**Comment by michaelbarton** [comment]
I think after the meeting #135 we agreed that if an optional directory, such as
`/bbx/metadata` or somthing similar, is mounted then log data and so forth
should be placed here. Does that seem reasonable? If correct I think we would
update the base biobox RFC with respect to this.

**Comment by michaelbarton** [comment]
We also agreed that output should go into `/bbx/output` instead of
`/bbx/output/bbx`.

**Comment by michaelbarton** [comment]
I think we'd need to add the log directory to the validator directory too. A
feature test to ensure that if it is mounted, then log data is placed here.

**Comment by michaelbarton** [comment]
It may be useful to specify all logs are processed to a consistent location,
e.g. `/bbx/metadata/log.txt`.

**Comment by pbelmann** [comment]
I removed the output bbx in rfc,validator and the available bioboxes

**Comment by pbelmann** [comment]
rfc, validator and the available bioboxes are now producing a log.txt if /bbx/metadata is mounted

**Comment by michaelbarton** [comment]
Looks good. We're agreed on `/bbx/metadata/log.txt` for all bioboxes?

**Comment by pbelmann** [comment]
I think it is a good idea to use this for all bioboxes, so I created a more general restructure issue #147 .
