### ISSUE TITLE
Bioboxes should provide a validator for the binning container

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#137]
@pbelmann has created an RFC for the binning container. We aim to provide a
validator for each type of biobox as this makes it simpler for biobox
developers to ensure their biobox matches the specification. The binning biobox
is however a more difficult case as it requires large reference databases to
compare against.

**Comment by michaelbarton** [comment]
@pbelmann do you think it might be possible to provide a small bioboxes dummy
database for testing? For example something a few megabytes in size? If I have
understood the RFC correctly, you could specify this as part of the `databases`
section in the biobox.yml?

**Comment by pbelmann** [comment]
I'm afraid that when I make the database smaller a binning bioboxes might not work as expected, so I will concentrate on building a bioboxes service.
If this does not work for whatever reason, I will reconsider providing a smaller database.

**Comment by pbelmann** [comment]
I think if a binning tool developer is using any database(ncbi, taxonomy, refseq, ...) he has to download the database anyway and mount it to his tool. So I created a validator for bioboxes [binning tools](https://github.com/bioboxes/validator-binning). If the developer is using one of the databases he can mount it to the validator by using one of the following parameters:

*  -R, --REFSEQ /path/to/your/refseq/database

*  -T, --TAXONOMY /path/to/your/taxonomy/database

*  -N, --NCBI /path/to/your/ncbi/database

*  -C, --COG /path/to/your/cog/database

*  -B, --BLASTDB /path/to/your/blastdb/database

This way the validator builds the yaml by using the definitions in the rfc and mounts the provided databases.

**Comment by michaelbarton** [comment]
Great Peter. I looked at the validate script in the code - you're cycling through each of these options when you're testing each binning container or each one has a specific arguments?

**Comment by pbelmann** [comment]
This part in the validate script:

https://github.com/bioboxes/validator-binning/blob/master/src/validate#L17-L54

1. Checks which argument is provided to the validate script.
2. Depending on the argument provided to the script it builds a yaml and a docker command used in the cucumber test.

The reason for this is that if you are using one of the databases listed in the [rfc](https://github.com/bioboxes/rfc/blob/master/container/binning/rfc.mkd#databases-definition) you have to mount it to the container and build the yaml used in the cucumber tests.
