### ISSUE TITLE
Biweekly review meeting - Fri May 22 08:00 UTC

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#140]
Germany - 10.00am
UK      - 09.00am

@bioboxes/core-team Please note the updated time and date, I will be in the UK
on this day so we can do the meeting in the morning. We will use the [Google
Hangout][gh] created by @avilella since this is accessible by everyone.

[gh]: https://plus.google.com/hangouts/_/gvbsoinmgxbqe7fbeoikkpwbkma

**Comment by fungs** [comment]
I will be on vacation this week.

**Comment by pbelmann** [comment]
Summary:

* A biobox should lists its tasks.

* All available bioboxes should be listed on bioboxes.org.

* Continue to work on profiling and binning interfaces.

* Bioboxes will be presented in the CAMI Evaluation meeting in Berlin.
