### ISSUE TITLE
The documentation of the bioboxes website should be automatically validated

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#142]
In issue #123 it was highlighted that the documentation can become stale.
Examples of this may be incorrect code or where the software provided by
bioboxes moves faster than changes to the documentation. I believe we need a
way to validate the documentation to ensure that it is always correct for
users, and generates an alert in the cases where it is not.

**Comment by pbelmann** [comment]
In PR bioboxes/bioboxes.org#40 I added the functionality to load and show code from a github repository by specifying the url. As long as the repository is correct (I will soon add a Bioboxes CI for every repository), the displayed code is correct, too. 

If we agree on this, we could extend this functionality by specifying a range of lines that is displayed from a remote source, like the already available github functionality: 
 https://github.com/bioboxes/velvet/blob/master/Dockerfile#L4-L5

**Comment by michaelbarton** [comment]
Thanks Peter. If I have understood correctly, when a url is the only contents of a code block, then this url will be fetched the contents will be used inside the code block?

**Comment by pbelmann** [comment]
exactly Michael. The disadvantage of this approach is that when you have about 40+ code blocks that must be fetched from github it will slow down the webpage. But I don't think that this will ever happen.

**Comment by michaelbarton** [comment]
I think this is a good idea. It will keep the code up to date with the live
repositories which are being used, and as you wrote, tested.

I've created a pull request with some suggestions. I use a helper function in
`helpers/code_blocks.rb` instead of an extension. This helper can be used in
the markdown and will fetch the github code when used. It will replace itself
with a markdown code block from the fetch and so can be parsed similarly to the
existing pages. For this reason I added back the code_block.js file. I've put
an example in `source/guide/developer/create-a-task.mkd.erb`. The `.erb`
extension must be added for these to preprocessed with erb prior to kramdown.

I thought that we should use the master branch for these fetched code block
examples. If we use other branches, then this could mean the pages would needed
to be updated when these branches are merged/deleted.

**Comment by pbelmann** [comment]
> I thought that we should use the master branch for these fetched code block
examples. If we use other branches, then this could mean the pages would needed
to be updated when these branches are merged/deleted.

I agree.

At the moment I'm referencing the developer_guide branch in velvet. It has many long comments for developers that are not familiar with shell programming. I will create a PR in velvet so that we can delete the other branches.

**Comment by pbelmann** [comment]
@michaelbarton I merged your PR bioboxes/bioboxes.org#41
 
I added another one (PR bioboxes/bioboxes.org#42) with the extension to load partial code blocks.

**Comment by pbelmann** [comment]
Bioboxes.org shows code blocks directly from github repositories.

**Comment by michaelbarton** [comment]
Using the line numbers to select specific parts of the file is a good idea.
