### ISSUE TITLE
Evaluation Format

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#145]
Bioboxes evaluation containers in version 0.8.x used to have one output definition that was just the output folder of the container.
In my opinion the evaluation containers 0.9.x must describe what is actually produced by the container with a format that can be used for any kind of evaluation.
In PR #144 I have added a format that @fungs,  @algbioi and I have initially created for binning and profiling evaluation.
 
Any feedback would be welcome.

**Comment by michaelbarton** [comment]
I think it's a good idea to have a generic evaluation container. The output
directory was too ambiguous and may not be too useful. I think this can
replace the genome assembly evaluation container.

My initial thought after read the RFC, is might the evaluator API be
simplified to two files a plain text file describing all the available
files, and a key-value CSV of metrics? I think it is additional work for
the developers to generate a YAML description of the output files when we
would expect the names of files etc., to change from evaluator to
evaluator.

**Comment by pbelmann** [comment]
You are right that in the case of representing just a list of csv files it would be easier to not use yaml. But if your evaluation creates png's or a mix of different file types then in my opinion a yaml is the right choice.

But I think we have two options:
 
  * A format that is flexible but complex (yaml structure). It can be used by any kind of evaluation but it is maybe not that easy to implement.
 
  * A format that has an easy structure. It is easy to implement (list of csv files) but it can not be used by any kind of evaluation.

Both options make sense.

**Comment by michaelbarton** [comment]
It could be simpler to not list all the files that are generated. For example if there was a file 'analysis_output.png' this would be specific to only this image, and you wouldn't expect it to be generated by different evaluation images.

My alternative suggestion is to specify only two files. A two-column key-value CSV of metrics generated (n50, #contigs, etc), and the second file that contains a text description of what all the generated files are.

**Comment by pbelmann** [comment]
Micheal could you make an example.
Do I understand that correctly?

1.
```TSV
n50        42
#contigs   84
.
.
```

This will not work when you want to include metrics that consists of more then one number.
I'm not sure how the second file should look like.

2.
```TSV
analysis_output    /path/to/analysis_output.png
special_metric      /path/to/special_metric.png
.
.
```

> It could be simpler to not list all the files that are generated. For example if there was a file 'analysis_output.png' this would be specific to only this image, and you wouldn't expect it to be generated by different evaluation images.

You are right it would be specific to this image. But I can not see the problem here since every evaluation image will have different outputs anyway. One advantage of the yaml would be to have a description of the output that can be parsed and displayed on a webpage. 

The quast image could have a default task that generates just the following yaml

```YAML
version: 0.1.0
results:
  - title: Basic Metrics
    type:
      name: tsv
    data:
      reference: /path/to/combined_results/reference.tsv
```  

The next step could be to create a task that includes the produced pngs.

**Comment by michaelbarton** [comment]
Is the aim of the evaluation output yaml to parse a list of files and display them on a webpage? Would you take the list of files or metrics in the yaml and display all of them on a webpage or would it be the case that the developer would select which are important?

**Comment by pbelmann** [comment]
> Is the aim of the evaluation output yaml to parse a list of files and display them on a webpage? 

I think displaying it on a webpage is one use case, yes. The yaml should allow you to postprocess the output. (You could for example filter all tsv files, if you don't want to show pngs) 

> Would you take the list of files or metrics in the yaml and display all of them on a webpage or would it be the case that the developer would select which are important?

It depends on what the task of the image would produce. If the default task in quast case returns just the path to the reports file and maybe the path to an image or svg file then I would display all of them.

**Comment by michaelbarton** [comment]
Using quast as an example, I take all the metrics I need from the 'report.tsv'
file. When I used quast for the first time I'd need to know that these metrics
are in the this file called 'report.tsv'. Each time I use quast afterwards I
can go straight to this file and get the metrics. If I started using a
different tool other than quast I'd need to know what the name of the file is
that contains the metrics I might want then start fetching them from there. 

I don't think I would use the proposed yaml file to find the file I want,
unless each yaml file in each different evaluator image specified 'Basic
metrics' entry, then I could look for the file using this key.

**Comment by pbelmann** [comment]
> I don't think I would use the proposed yaml file to find the file I want,
unless each yaml file in each different evaluator image specified 'Basic
metrics' entry, then I could look for the file using this key.

I see. An ontology would solve this issue. But I think it is impossible to create an ontology for the variety of evaluation metrics.

Ok then what if we use a simpler yaml structure that allows us to display the metrics and for each metric not only a single value entries but also different values:

```YAML
- name: STRING
  description: STRING
  value: ANYTHING
- name: STRING
  description: STRING
  value: ANYTHING
```

The value type could be for example a timeseries.
This way we would not be restricted to single value metrics.

**Comment by michaelbarton** [comment]
> An ontology would solve this issue. But I think it is impossible to create an ontology for the variety of evaluation metrics.
I  agree. We could consider this in future if there were multiple evaluators of the same type.

> Ok then what if we use a simpler yaml structure that allows us to display the metrics and for each metric not only a single value entries but also different values.

I agree. I like this format.

**Comment by pbelmann** [comment]
yesterday @algbioi and I containerized binning evaluation scripts that are following the new upcoming binning evaluation interface. When we started to describe the output by using a yaml:

```YAML
- name: STRING
  description: STRING
  value: ANYTHING
- name: STRING
  description: STRING
  value: ANYTHING
```

We started to copy the produced files inside the yaml and what we noticed is that it became difficult to read and to understand. That's why we started again to produce an output yaml like:

```YAML
- name: STRING
  type: csv
  value:  VALUE
  inline: true 
- name: STRING
  type: txt
  value: VALUE 
  inline: false
```

As @michaelbarton  mentioned in quast case it makes no sense to reference the produced files, instead we should include them. But if your evaluation method produces output like:

```CSV
# precision, recall, #classes precision, #classes recall, seq. count/bp, weighted bins
superkingdom,--,--,--,----------,----------
100.0, 100.0, 2, 2, "count", "not weighted"
100.0, 100.0, 2, 3, "bp", "not weighted"
100.0, 100.0, 2, 2, "count", "weighted"
100.0, 100.0, 2, 3, "bp", "weighted"
phylum,--,--,--,----------,----------
100.0, 100.0, 5, 3, "count", "not weighted"
100.0, 100.0, 5, 5, "bp", "not weighted"
100.0, 100.0, 5, 3, "count", "weighted"
100.0, 100.0, 5, 5, "bp", "weighted"
class,--,--,--,----------,----------
100.0, 100.0, 5, 3, "count", "not weighted"
100.0, 100.0, 4, 5, "bp", "not weighted"
100.0, 100.0, 5, 3, "count", "weighted"
100.0, 100.0, 4, 5, "bp", "weighted"
order,--,--,--,----------,----------
100.0, 100.0, 5, 3, "count", "not weighted"
100.0, 100.0, 5, 6, "bp", "not weighted"
100.0, 100.0, 5, 3, "count", "weighted"
100.0, 100.0, 5, 6, "bp", "weighted"
family,--,--,--,----------,----------
100.0, 100.0, 9, 6, "count", "not weighted"
100.0, 100.0, 10, 11, "bp", "not weighted"
100.0, 100.0, 9, 6, "count", "weighted"
100.0, 100.0, 10, 11, "bp", "weighted"
genus,--,--,--,----------,----------
100.0, 100.0, 10, 7, "count", "not weighted"
100.0, 100.0, 11, 11, "bp", "not weighted"
100.0, 100.0, 10, 7, "count", "weighted"
100.0, 100.0, 11, 11, "bp", "weighted"
species,--,--,--,----------,----------
0.0, 100.0, 0, 1, "count", "not weighted"
0.0, 100.0, 0, 1, "bp", "not weighted"
0.0, 100.0, 0, 1, "count", "weighted"
0.0, 100.0, 0, 1, "bp", "weighted"
```
it makes no sense to include it in a yaml. 
That's why I think we should use a parameter to reference files.

**Comment by algbioi** [comment]
I think, we should explain more precisely what the aim of the yaml file is and then whether the proposed solutions satisfy that. 

The aim is to provide meta-information about the output files produced by an evaluation container to:
- enable automated post-processing of the data (e.g. displaying it on a web side)
- distinguish between important files containing evaluation results (metrices) and temporary files
- provide additional information about the files (e.g. metric explanation or file format)

Some of the solutions already satisfy some of the requirements, my favourite is the last one, where I would add attribute “description”; as a "value", I agree, we can use a string or reference a file.

**Comment by pbelmann** [comment]
Thanks @algbioi .
I simplified the interface according to the discussion on this thread. I will merge the current definition since it satisfies the requirements mentioned in this thread. @michaelbarton I tagged the interface with the version number 0.1.0. If we encounter further problems we can open a new issue, update the format and change the version number.
