### ISSUE TITLE
Bioboxes should list all available Bioboxes

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#148]
As discussed in https://github.com/bioboxes/rfc/issues/140 all available Bioboxes should be listed in a file.
That will help us in
 
* a GUI to list and run Bioboxes

* providing a catalog of all Bioboxes on bioboxes.org

As a first version I created a repo with an image listing.

https://github.com/bioboxes/data

For this I adapted @michaelbarton s yaml

https://github.com/nucleotides/nucleotides-data/blob/master/data/image.yml

**Comment by michaelbarton** [comment]
Implemented
