### ISSUE TITLE
Allow other, more efficient, compression formats for input data.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#15]
Gzip is an inefficent compression algorithm where other algorithms such LZ4 can
provide better compression with a small time trade-off, while LZMA provides
much larger compression ratios with a greater time trade off. The specification
should in future consider the data being provided independent of the
compression format as discussed in #10.

**Comment by fungs** [comment]
Here is an incomplete list of compression programs with different time-space trade-offs from fast to slow. Maybe this helps when implementing some more general approach:

lz4
lzop
gzip/pigz
bzip2/pbz2
xz/pxz

I would only consider formats which are able to do stream compression.

**Comment by michaelbarton** [comment]
Different compression formats would be useful to consider, however there are
more urgent priorities for bioboxes in the short-term. This issue will be
closed and should reopened when it becomes a priority again in future.
