### ISSUE TITLE
Register a domain and create a website for bioboxes

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#16]
Should we consider registering a domain for sibci if are hoping for wider
adoption of this RFC by the community? The .org domain for sibci is available
and is inexpensive. We could create a website that could be easier to browse
than the RFC markdown document. This might be particularly useful as the
document becomes larger and larger with the likely inclusion of more container
specifications.

**Comment by michaelbarton** [comment]
I will add this to milestone v0.9.

**Comment by michaelbarton** [comment]
The domain bioboxes.org is registered.

**Comment by fungs** [comment]
Maybe start with bioboxes.github.com

**Comment by michaelbarton** [comment]
I will deploy the website site on AWS S3 as static HTML files. I have set up
the domain registrar DNS records for bioboxes.org to point to those provided by
Route 53.

**Comment by michaelbarton** [comment]
Created a git repository for the website:
https://github.com/bioboxes/bioboxes.org

**Comment by michaelbarton** [comment]
The website is set up to build on circleci:
https://circleci.com/gh/bioboxes/bioboxes.org

**Comment by michaelbarton** [comment]
The website is now live (bioboxes/bioboxes.org#1). The website is built using
the middleman rubygem and deployed to S3 upon a successful commit to the master
branch. The domain URL is http://bioboxes.org. Anyone can now make pull
requests to this project and once merged will immediately be visible.

**Comment by fungs** [comment]
Consider setting an alias in the DNS record for www.bioboxes.org
