### ISSUE TITLE
Create mail@bioboxes.org email address

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#160]
This will be useful signing up for things. Ideally we should use a CRM, however
I do not know a good free one we can use.

**Comment by Leprevost** [comment]
I can configure a mailgun account and then create individual emails and routes.

**Comment by michaelbarton** [comment]
Yes I think this would be very helpful. I can configure the MX if necessary.

**Comment by michaelbarton** [comment]
I'm attempting to set up mail forwarding from the name registar for the
bioboxes domain. I've set up the MX records and will try sending an email after
this has had time to propogate.

**Comment by michaelbarton** [comment]
This email address is working now and we can use this in the maintainer field in Dockerfiles.

**Comment by fungs** [comment]
Hi @michaelbarton and @Leprevost, does it make sense to set this primary email address as a mailing list, if it is going to be used as the maintainer address in the Dockerfile for bioboxes.org provided bioboxes?

**Comment by michaelbarton** [comment]
I think a mailing list would be a good idea for another forum and point of contact. If this were to be the maintainer field in the Docker files then it should be something like `public-email-list@bioboxes.org` to make it clear that any email going to that address would be public.

**Comment by fungs** [comment]
What I meant was basically an internal mailing list (or better mail forward) to those that created the bioboxes. With multiple creators and one maintainer address this seems useful to me.
