### ISSUE TITLE
The binning validator should be available for download

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#161]
The binning validator needs to be available for download from S3.

**Comment by michaelbarton** [comment]
@pbelmann there was an error running the tests on circleci -
https://circleci.com/gh/bioboxes/validator-binning/1

Does this look an image error or a circleci error?

**Comment by michaelbarton** [comment]
I think perhaps it is that unshuffle_fastq.pl, run.sh, and unshuffle_fastq.pl
need the executable permission?

**Comment by michaelbarton** [comment]
Currently the file-deployer image is not building on dockerhub, I may need to
create a support ticket to resolve this.

https://registry.hub.docker.com/u/nucleotides/file-deployer/builds_history/230760/

**Comment by pbelmann** [comment]
I will test it. But it seems to be an lxc error.

**Comment by pbelmann** [comment]
Ok it works now. It was a permissions issue. 
https://circleci.com/gh/bioboxes/validator-binning/5

**Comment by michaelbarton** [comment]
@pbelmann could you look at this failing test - https://circleci.com/gh/bioboxes/validator-binning/9.

I've setup the deployment container, it should theoretically deploy the tool once the tests pass, though there may still be some wrinkles.

**Comment by pbelmann** [comment]
The test works now. S3publish script is still failing.
