### ISSUE TITLE
Biweekly review meeting - Thu 16 Jul 2015 15:00 UTC

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#167]
* UK time 4pm
* Germany 5pm
* California 8am

The hangouts link will be posted in this thread. 
@bgruening will join this call, if he has time. We talked about Docker and standards at BOSC.
Björn if you don't have time, maybe you can summarize your proposal, so that we can discuss it in the meeting.

**Comment by bgruening** [comment]
I have a workshop at this time, but maybe I can delegate this for an hour :)

My proposal was to have a layered spec for building docker containers. Every spec is one Docker fs-layer.
The community is in need to have standardised Docker containers and bioboxes does a great job here. My feeling is that we need some specs that define how to build and create Docker containers and ontop of this we can add the bioboxes magic from today.
For example it would be nice to define how the ENTRYPOINT is used, which volumes are exported, which base system we want to use ... I know these are basic problems and can be resolved quickly, but I feel this needs to be the groundwork that is needed.

My stretch goal would be to create containers for all tools in brew/guix with an automatic script leverage a unique interface that can be consumed by the current bioboxes spec.

Hope to see you all on Thursday.
Bjoern

**Comment by michaelbarton** [comment]
Thanks for setting up the meeting @pbelmann.

@bgruening, I will look forward to hearing your ideas.

**Comment by michaelbarton** [comment]
Google hangout - https://plus.google.com/hangouts/_/g4csq3sthv7bp5fe62ojzqjhbma

**Comment by bgruening** [comment]
Sorry, workshop just ended now :(

**Comment by michaelbarton** [comment]
@bgruening Sorry that you missed the meeting, we did discuss your suggestion though. Would it be possible for you to provide us with an example? It would be easier us for to understand with an implementation.
