### ISSUE TITLE
too much emphasis on genomics

### ISSUE THREAD

**Issue by Leprevost** [bioboxes/rfc#170]
I noticed that there is a large presence of genomics content being used and cited. I think that if you want that this project be accepted by the general community, we must be careful  by not making 'bioinformatics' a synonym of 'genomics'. I have being working with proteomics for some years and believe me, the problems are the same as the genomics area.

I think that in the beginning is good to select an "area" or "problem" that is a hot topic to be addressed, like genome assemblers, for example, but it is also important to not pass the idea of being something for the genomics community only.

**Comment by michaelbarton** [comment]
Thanks for the suggestion, would you be able to provide a PR for this?

**Comment by michaelbarton** [comment]
Thanks for the suggestion. I have updated the commentary article to mention
proteomics.
