### ISSUE TITLE
Biweekly review meeting - Thu 30 Jul 2015 15:00 UTC

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#171]
* UK time 4pm
  * Germany 5pm
  * California 8am

The hangout link will be posted in this thread.

**Comment by fungs** [comment]
Is anybody posting the Hangout link?

**Comment by michaelbarton** [comment]
Trying to, I'm having problems getting it set up.

**Comment by pbelmann** [comment]
https://plus.google.com/hangouts/_/g32c3y7y3vota6ljtac43ucdsya

**Comment by fungs** [comment]
I'm on a good connection and it broke down, are you guys still there?

**Comment by fungs** [comment]
Maybe we can try this: https://hello.firefox.com/dD8U9HP8JK0
Should work with any modern browser.
