### ISSUE TITLE
Assing BioInterchange Docker image

### ISSUE THREAD

**Issue by indiedotkim** [bioboxes/rfc#173]
Would it be possible to add my [BioInterchange docker image](https://registry.hub.docker.com/u/codamono/biointerchange/) to the [available Bioboxes](http://bioboxes.org/available-bioboxes/) list? There is also a Dockerfile available for people who would like to build their own images; it is described [here](https://www.codamono.com/biointerchange/#docker-linux).

Thank you,

Kim

**Comment by michaelbarton** [comment]
Currently bioboxes Docker images follow specific defined specifications, which
allow them to be interchangable. The current specifications are for genome
assembly, read binning and read profiling. I believe biointerchange is outside
of these domains.

Thanks
