### ISSUE TITLE
Create bbx-base DockerHub trigger

### ISSUE THREAD

**Issue by fungs** [bioboxes/rfc#179]
In order to use the base image, which is subject to improvements, in Dockerfiles via

    From bioboxes/bbx-base

we need to set up an automatic build trigger for the corresponding GitHub repository

    bioboxes/bbx-base

**Comment by michaelbarton** [comment]
I created the 'bioboxes/base' automated build.

**Comment by fungs** [comment]
Build worked but does not show Dockerfile and extended info on
https://hub.docker.com/r/bioboxes/base/

@michaelbarton, do you know why this could be the case?

**Comment by pbelmann** [comment]
Maybe related to 
https://github.com/bioboxes/rfc/issues/179#issuecomment-135666340

**Comment by pbelmann** [comment]
I retriggered the build and the description is now available. https://hub.docker.com/r/bioboxes/base/

**Comment by fungs** [comment]
Strange, the README is showing but the Dockerfile is not. This must have to do with their new interface, it used to work well for for our CAMI images.

**Comment by michaelbarton** [comment]
I've had problems with dockerhub too. I'll retrigger the build again now.

**Comment by michaelbarton** [comment]
What is your dockerhub username @fungs?

**Comment by michaelbarton** [comment]
I have added you with 'write' access to this repository. This should allow you
to trigger a rebuild in future if there are any more problems.
