### ISSUE TITLE
Should a metrics file be specified by the assembly validator RFC?

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#182]
Should some sort of file be specified by the assembly validation RFC? For example I was looking at the verification code for the validator and it checks that the output bioboxes.yaml is created but not if an outputs metrics file is.

**Comment by pbelmann** [comment]
The biobox.yaml produced by the assembly validator represents the evaluation file (https://github.com/bioboxes/rfc/blob/master/container/assembly-evaluation/rfc.mkd)

**Comment by pbelmann** [comment]
@michaelbarton Can we close this issue?

**Comment by michaelbarton** [comment]
Issue bioboxes/rfc#204 will now specifically addresses this.
