### ISSUE TITLE
What bioboxes functions should be demonstrated at the simultaneous talks on November 9th?

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#184]
@pbelmann will be presenting bioboxes at the [Bio in Docker workshop][bid] by
@KHP-Informatics. @michaelbarton will be presenting the same day at the [UC
Davis Docker workshop][davis] organised by @ctb. I believe we should coordinate
what functionality we are presenting so that it will be consistent.

[bid]: http://core.brc.iop.kcl.ac.uk/events/compbio-docker-symposium-2015/
[davis]: https://dib-training.readthedocs.org/en/pub/2015-11-09-docker.html

**Comment by michaelbarton** [comment]
Here are some initial suggestions:

  * Merge in the CLI 0.3.0 branch to master, as this contains a lot of new
    functionality and fixes.

  * Demonstrate using the CLI to assembly the same sets of reads with different
    assembly bioboxes.

  * Demonstate chaining together the signatures and biobox.yaml files by
    running the assembly validator biobox on the output of the validator
    bioboxes.

**Comment by ctb** [comment]
+1 to all of these!

**Comment by michaelbarton** [comment]
An additional thought: these recipes will be generally useful all the time and not just at these presentations. I think we should add a recipes section the website for the existing bioboxes. One would be assembly and validation. A second would be binning and assembly. I don't think the signatures match up exactly in the latter case though.

**Comment by pbelmann** [comment]
@michaelbarton I send you my slides for the workshop. 

I want to present:

* cli with assemblers and assembly evaluation

* Alpha version of the bioboxes gui

* continuous evaluation as one use case of bioboxes (nucleotid.es and cami analysis page)

> An additional thought: these recipes will be generally useful all the time and not just at these presentations. I think we should add a recipes section the website for the existing bioboxes. One would be assembly and validation. A second would be binning and assembly. I don't think the signatures match up exactly in the latter case though. 

Yes we could prepare such a section, but I'm not sure if we should already start present chaining, since as you already mentioned it will not work with all signatures. This is something we still have to figure out.

What do you think?

**Comment by michaelbarton** [comment]
> * Demonstrate using the CLI to assemble the same sets of reads with different assembly bioboxes.
>
> * Demonstate chaining together the signatures and biobox.yaml files by running the assembly validator biobox on the output of several assembler bioboxes.

I have created a recipe page in bioboxes/bioboxes.org#52 which shows the above functionality. It doesn't however chain containers together using the yaml API but instead used the CLI.

**Comment by michaelbarton** [comment]
Closing this issue as presentations have been given.
