### ISSUE TITLE
Suggested changes to the assembly validator input interface

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#194]
I would like to change the input file format to the assembly validator interface. Currently an example input is:

~~~ yaml
---
version: 0.9.0
arguments:
  - fasta:
    - id: "1"
      value: "/bbx/input/assembly.fasta"
      type: contigs
  - fasta_dir: "/bbx/input/references"
~~~

I would like to change the last line to be something like:

~~~
  - fasta_dir:
    - id: "1"
      value: "/bbx/input/references"
      type: references
~~~

The reason for this, is that if every entry is in the form of id/value/type the host/container paths can be automatically remapped and the docker volume strings being created.

@pbelmann unless you have any objections, I would like to implement this.

**Comment by pbelmann** [comment]
I don't have any objections. For the next major release of an interface we should discuss changing from array values to properties. But this is a different issue.

**Comment by michaelbarton** [comment]
I agree. I think the biobox.yaml file format is worth revisiting.

**Comment by michaelbarton** [comment]
I have implemented the new API format in bioboxes/quast#8. I have disabled the
tests because there is a circular dependency between the biobox CLI tests and
the QUAST biobox. Specifically the quast image verification tests and the image
unit tests are bootstrapped on each other.

**Comment by michaelbarton** [comment]
I have implemented support for running the new QUAST API in the bioboxes.py
python library. This was merged in bioboxes/bioboxes-py#16

**Comment by michaelbarton** [comment]
I have created pull request bioboxes/command-line-interface#96 to implement
support for this in the the biobox CLI.

**Comment by michaelbarton** [comment]
@pbelmann I integrated the bioboxes.py library into the command line tool in
bioboxes/command-line-interface#98. One of the main advantages of the
bioboxes.py library is that it takes advantage of the Docker container mounted
directories not needing to be named by the user. To put this another way, the
developer or the user doesn't need to name the directories when mounting them
into the container as long as they match the paths in the biobox.yaml. The
biobox.py library takes care of this by creating the Docker volume strings and
then updating the biobox.yaml with the container-mounted locations. [If you
compare this diff form the PR][diff] for the short read assembler, you see see
this simplifies running a biobox. In this update, only the biobox.yaml with
host-paths needs to be supplied and the biobox.py library takes care of the
mounting and creating biobox.yaml with the container paths.

[diff]: https://github.com/bioboxes/command-line-interface/pull/98/files#diff-a177eca341ed3a8072193cdce96fc57bL31

This should simplify implmenting bioboxes/command-line-interface#8, and all
future implementations of bioboxes in the CLI. An additional advantage is that
the bioboxes.py also accepts Docker images in the format of repo/image@sha256,
where as previously I think there were problems when trying to use the sha256.

**Comment by pbelmann** [comment]
Looks good Michael. Thanks for implementing this.
I think we can close this issue.
