### ISSUE TITLE
Interface for read mappers?

### ISSUE THREAD

**Issue by sdwfrost** [bioboxes/rfc#196]
I've doing some work on read mapping of viral sequences, and to add value, I'd like to build Bioboxes for read mappers such as [SMALT](http://www.sanger.ac.uk/science/tools/smalt-0), [NextGenMap](http://cibiv.github.io/NextGenMap/) etc. How does one propose a format to have something like:

```
docker pull bioboxes/smalt

biobox run \
  read_mapper \
  bioboxes/smalt \
  --input reads.fq \
  --reference ref.fa \
  --output alignment.bam
```

Is there a convention for the flags for paired end read files as well as how to use program-specific flags?

**Comment by pbelmann** [comment]
Hi Simon,

> How does one propose a format

the first step would be to create an rfc like this one: 
https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd

If you could create a pull request with an rfc, we would implement the command line interface for the biobox command line python tool.

> [...]  how to use program-specific flags?

Program specific flags are listed in a file like this one [here](https://github.com/bioboxes/velvet/blob/master/Taskfile) .

A task like "default" or "careful" would be specified after the image name:

~~~BASH
biobox run \
  read_mapper \
  bioboxes/smalt \
  default \
  --input reads.fq \
  --reference ref.fa \
  --output alignment.bam
~~~

> Is there a convention for the flags for paired end read files [...]

In case of the short read assembler interface we simply stated in the biobox.yaml whether the input is single end or paired end as you can see [here](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd#fastq-definition)

**Comment by pbelmann** [comment]
@sdwfrost If you still interested in a read mapping interface for bioboxes, please reopen this issue. We would be glad, to help you with this.
