### ISSUE TITLE
Need to define a license for all the code and bioboxes we are creating.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#198]
Currently all of the bioboxes code in unlicensed on github which leaves us in an ambiguous situation with regard to others using this code.

@pbelmann could you provide me a full list of all the institutions and their IP departments at your end who have committed actual code to this? I will follow up with our IP department once I have this. This is a high priority as we need to resolved any possible issues that might arise out of this.

**Comment by tfmorris** [comment]
I don't see the ambiguity. Authors are granted a copyright immediately when they fix the code in a tangible expression. Depending on their employment agreement, their employer may actual own that copyright. Lacking a license, the only way people can reuse the code is through the "fair use" exception to copyright, which almost no organizational lawyer would except as a path forward.

Given that state of affairs, the code is, I would argue, unambiguously unusable.

**Comment by michaelbarton** [comment]
@tfmorris, yes you are correct. This should be a priority for the project.

@pbelmann, could you follow up with the data I requested as soon as possible? I believe the two institutions are yours and that of Alice McHardy's group.

**Comment by pbelmann** [comment]
@michaelbarton  the following institutions are involved: 

* Bielefeld University 

and

* Helmholtz centre for infection research

**Comment by michaelbarton** [comment]
Thanks Peter. I've contacted our IP lawyers here, I'll follow up when I have more details.

**Comment by michaelbarton** [comment]
I'm going to meet with the lawrence berkeley lab IP office on Feb 27 to discuss this licensing issue.

**Comment by michaelbarton** [comment]
Bioboxes are now licensed under Apache 2.

[bioboxes_license.txt](https://github.com/bioboxes/rfc/files/1540522/bioboxes_license.txt)

**Comment by tfmorris** [comment]
Cool. Thanks for sorting it out!
