### ISSUE TITLE
Definine a new data format for listing images with the SHA256 digest

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#200]
Multiple versions of a biobox docker image will exist when developers release
new versions. The bioboxes/data repo should track these versions using SHA256
digests as these are supported natively by docker.

I am already using these in the nucleotides [list of images][list] and I
propose we define a format incorporating the two. I can then switch to using
this list for the nucleotides benchmarking.

[list]: https://github.com/nucleotides/nucleotides-data/blob/master/inputs/image.yml

**Comment by pbelmann** [comment]
@michaelbarton  I'm also interested in this, so set up a [PR](https://github.com/bioboxes/data/pull/6) with SHA256 digests. Please close this issue if you agree.

**Comment by michaelbarton** [comment]
Peter, this looks good. I think I should be able to import the current
nucleotides image list using this format. One question I have is how to manage
multiple pubmed entries for different software versions. For example if a
later version of the same assembler has a follow up publication. I would
suggest making pubmed entries a list of IDs instead of a single one? This
might be simpler to manage as opposed to trying to tie each Docker image
version to a particular publication. What do you think?

**Comment by pbelmann** [comment]
> I would suggest making pubmed entries a list of IDs instead of a single one?

It makes sense Michael. Would you incorporate the additional pubmed ids?

**Comment by michaelbarton** [comment]
As far as I know, there aren't any software that currently has multiple pubmed
IDs. My reason for clarification was as to whether we should track the
publications at the version level, or the top image level.

**Comment by pbelmann** [comment]
I would say at the top level. See updated [PR](https://github.com/bioboxes/data/pull/6)

**Comment by michaelbarton** [comment]
PR merged in and issue closed.
