### ISSUE TITLE
Proposal for bioboxes version v0.9: interface validators.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#35]
### Motivation

I believe a good standard requires validators so that implementors may check
their version is compliant. Using the syntax proposed in issue #9, given an
image implementing the following hypothetical interface:

    f: X → Y

Then a validating image would provide this interface:

    f: (X → Y) → Bool

The first argument here is an image with the interface (X → Y) and the output
is a true or false value as to whether this the image is valid. Each
specification already has values defined about the required inputs and outputs
so we would not need to update the specs any further. We would instead create
Docker images which take an image and then test their interface against the
spec with real data to see if they perform correctly.

I believe this will be very important as SIBCI continues to grow because I have
recieved containers for nucleotid.es from third-parties that have not worked as
expected. I have then had to manually debug them myself. If we can automate
this testing, then I think this will save us and others time because there will
be a much quicker feedback loop on whether an images complies with the spec.

### Implementation

I have been experimenting with testing the genome assembly benchmarking
interface:

    f: [A] → [A] → [(K,V)]

Which takes two lists of FASTA entries and should return a list of key-value
pairs. I have been able to create a simple test suite for this using CircleCI
which can be found here:

https://circleci.com/gh/nucleotides/docker-quast/13

I believe this test suite can be wrapped up inside an image that performs these
tests when given the name of another image. This container will then return a
T/F value determining whether the image is valid according to the spec.
Furthermore if we use CircleCI to validate the images we will get information
on whether a PR to an image is valid as the information will automatically be
added [using the github API](http://blog.circleci.com/github-status-support/).

**Comment by michaelbarton** [comment]
I think each specification should have the name of the validating image as part
of the spec so that it can be quickly identified and allow third parties to
begin using it. The image and the spec should ideally have the same version
number because an update to the spec necessitates a change to the image.

**Comment by pbelmann** [comment]
I will give it a try in the next days.

**Comment by michaelbarton** [comment]
I have been working on a image to validate the CAMI/nucleotid.es short read
assemblers. I have been experimenting so far with using Docker-in-Docker
(dind). This will provide a docker daemon running inside a container which,
given an image name, can validate the assembler against the specification. The
current repository for this is:

https://github.com/bioboxes/validator-short-read-assember

**Comment by michaelbarton** [comment]
The dind image now successfully builds on circleci. An example build is here:

https://circleci.com/gh/bioboxes/validator-short-read-assember/12

The ideal end product of this issue is that all bioboxes are checked against
the spec using continuous integration such as with @circleci. This would mean
we could get an immediate answer as to whether a biobox image is valid.

Taking this a step further, related to the discussion with @ScottBGI on
issue #47, a journal such as @gigascience could have a form in the manuscript
submission area where the name of a docker image associated with the article is
provided. The author's image could be immediately checked with the validation
image and the submitting author would get an answer as to whether the image was
valid or not. This could streamline the review process, remove some burden from
the reviewers, and ideally prevent the publication of buggy non-working
bioinformatics software.

**Comment by michaelbarton** [comment]
I have created a simple validator for the short read assembler, I think this could be used at a template for other validators. I have created a short video outlining how it works - http://youtu.be/Y59uhI0b1CA

**Comment by Leprevost** [comment]
@michaelbarton , very interesting ideas, I didn't knew dind before. What is your idea about getting files inside and outside the containers? Normally I set a shared folder between the container and the host and then both can have access to files, but maybe this can be achieved in a more generic way, like using another container as "gateway".

**Comment by asczyrba** [comment]
@michaelbarton Docker in Docker might not be optimal solution, as you need to use the --privileged flag when starting the container. That again means that you get absolutely no security  and your isolation is the same isolation you get by running a program with the same user id directly in your host

**Comment by asczyrba** [comment]
I just came across this article describing "copying data between docker containers":

https://medium.com/@gchudnov/copying-data-between-docker-containers-26890935da3f

**Comment by michaelbarton** [comment]
@Leprevost for a standard bioboxes the input data should be mounted as a
read-only volume and it's location specified some how. For output data there
should be a writeable volume mounted. We haven't investigated gateway
containers - docker calls this the [ambassador pattern][amb].

[amb]: https://docs.docker.com/articles/ambassador_pattern_linking/

Validation should not need to mount any data. My idea was they would container
all the data they need to use to validate a biobox's inputs and outputs.

**Comment by michaelbarton** [comment]
@asczyrba I agree that `--privileged` is a security concern. In the case of
using continuous integration this won't matter since it's spawned on a
temporary node. I envision this should be most common use case for bioboxes, so
that we don't have to manually test containers when we're given them. We could
maintain list of bioboxes of each type and then circleci could test each
container on the list whenever a PR is given.

The main problem of `--privileged` would be if a user is using it on their
local system. I'm happy to see an alternative implementation if you think this
can be done with copying. Ideally the solution should be a single command to
run the container against varying outputs, ensure the container ran to spec,
and that the generated outputs are correct.

**Comment by avilella** [comment]
Just to add to the info, arvados uses --privileged because they also run
docker-inside-docker as part of their system.

There are a couple of arvados guys in the CWL group, so they may have some
ideas around this area.

A.

**Comment by michaelbarton** [comment]
Discussed in meeting #67. Validators are still a priority. These will start
being implemented once a specification is agreed for passing data to bioboxes
(#61, #86).

**Comment by michaelbarton** [comment]
This has been implemented or is being implemented for all biobox types.
Therefore this issue can be closed.
