### ISSUE TITLE
Use a different name other than SIBCI

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#40]
The name SIBCI was chosen quickly by myself when writing the initial draft of
the spec. This name however appears to be a bad choice as SIBCI is already used
by [the Bolivian revolutionary government][sibci] and already has many
mentions on twitter. I therefore propose we quickly adopt a new name with the
following guidelines based on [a blog post by Keith Bradnam][blog]:

  * The twitter handle and domain name are available
  * There should be a limited number of google hits to the name.
  * The name gives an indication of what the project is about, and therefore
    need not necessarily be an acronym. I would go a step further and say that
    there are many acronyms in bioinformatics and perhaps we should even avoid
    one.
  * The name should be easily pronounceable and ideally easily spellable from
    the pronounciation.

[sibci]: https://twitter.com/sibciguarico
[blog]: http://www.acgt.me/blog/2015/1/22/from-casp-to-poreathon-what-makes-for-a-good-bioinformatics-brand-name

**Comment by michaelbarton** [comment]
A few ideas from browsing terms related to shipping:

  * BioAssets
  * BioFreight
  * BioInterModal

Other ideas:

  * unitenere    - Latin: units of holding
  * containelles - composition of containers and organelles
  * endotainers  - endo + containers
  * Golgi Boxes  - Golgi apparatues + boxes

**Comment by avilella** [comment]
- Ace of Base: a place to "ace" your nucleotide "bases"

**Comment by michaelbarton** [comment]
I also have the domain http:/conti.gs. We could use this and follow a similar
path to http://nucleotid.es where the name is also the URL. This has proved
quite fruitful on twitter as "nucleotid.es" becomes a clickable hyperlink in
the tweets.

**Comment by kbradnam** [comment]
How about something simpler still like BioBox or BioBoxes? Both have been used by others but the latter seems to have twitter account available and there's not too much usage of it which would overlap with your intended use. 

If you were prepared to hyphenate it, you could probably have more chances of making it unique.

**Comment by michaelbarton** [comment]
I like bioboxes, the .org domain is available too.

**Comment by pbelmann** [comment]
I like BioBoxes. It meets all the criteria.

**Comment by kbradnam** [comment]
There is some previous overlap within the field of bioinformatics with APBioBox:

http://www.apbionet.org/grid/apbiobox/lsvgcApr04/index.shtml

This is from over a decade ago, and is not likely to cause confusion I think, especially if you went with the plural form (which makes more sense for you anyway).

**Comment by michaelbarton** [comment]
@kbradnam Thanks for your comments they are much appreciated and I think BioBoxes is an excellent and simple name.

**Comment by michaelbarton** [comment]
Since we have a simple consensus, I will change the name to BioBoxes.

**Comment by michaelbarton** [comment]
I have changed the github organisation name to 'bioboxes'. I also think that we should use all lower case to avoid any confusion about internal capitalisation, e.g. BioBoxes vs. Bioboxes.

**Comment by michaelbarton** [comment]
I have registered the twitter handle bioboxes

**Comment by michaelbarton** [comment]
I have registered the domain bioboxes.org

**Comment by avilella** [comment]
And biobox.es? 😀

**Comment by michaelbarton** [comment]
According to gandi.net this domain is [already registered](https://www.gandi.net/whois/details?search=biobox.es)

**Comment by michaelbarton** [comment]
Resolved by #41

**Comment by kbradnam** [comment]
Glad you could register the domain name and get the twitter account name.

I have one other minor comment…your current logo doesn't really feature anything biological. Also, given your new name, it would make more sense to me to have a log which features at least 2 boxes of some kind. I attach a mock up of the sort of thing I would imagine (DNA logo created by Darrin Higgins for the Noun Project)

![screen shot 2015-02-03 at 3 08 46 pm](https://cloud.githubusercontent.com/assets/2367600/6031737/d0b8a664-abb6-11e4-81b2-31508b63882e.png)

**Comment by kbradnam** [comment]
And one more iteration of the design to change the font and kerning, and make everything a bit 'boxier'
![screen shot 2015-02-03 at 3 17 52 pm](https://cloud.githubusercontent.com/assets/2367600/6031895/f6ec6b3a-abb7-11e4-93fb-04d7883f0ea8.png)

**Comment by michaelbarton** [comment]
Thanks for your suggestions @kbradnam, your input is very much appreciated. I agree that the current logo does not reflect the name bioboxes or it's relationship to biology. I suggest we continue this discussion on logo repository. I have opened the issue - bioboxes/logo#2. I have made further iterations in response to your suggestions.
