### ISSUE TITLE
Bioboxes v1.0 should be an adopted community standard.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#48]
* Create core team #44
  * Website with documentation and tutorials #16
  * Set of editor/reviewer instructions #35, #46
  * Published, peer-reviewed article #45
  * Major publishing groups agree to biobox standard #47

Software has proliferated in bioinformatics and unfortunately so have
the problems with using it: missing or unobtainable code, difficult to
install dependencies, secret usage recipes that are irreproducible,
all with terrible user experiences. We believe a community standard
for containers has the opportunity to solve these problems and thereby
increase the standard of scientific software as a whole.

We would like to ask anyone interested to help us make the version 1.0
of bioboxes. We want to fix these problems that exist in the field,
and make bioinformatics software readily available for everyone.

A standard for bioinformatics containers will move us towards a more
open environment for anyone to innovate, collaborate and share their
scientific results. By working in a truly standardized and
interoperable ecosystem, bioinformatics algorithmic development will
become more valuable and reach a wider userbase.

**Comment by avilella** [comment]
A few more ideas below:


Software has proliferated in bioinformatics and unfortunately so have
the problems with using it: missing or unobtainable code, difficult to
install dependencies, secret usage recipes that are irreproducible,
all with terrible user experiences. We believe a community standard
for containers has the opportunity to solve these problems and thereby
increase the standard of scientific software as a whole.

We would like to ask anyone interested to help us make the version 1.0
of bioboxes. We want to fix these problems that exist in the field,
and make bioinformatics software readily available for everyone.

A standard for bioinformatics containers will move us towards a more
open environment for anyone to innovate, collaborate and share their
scientific results. By working in a truly standardized and
interoperable ecosystem, bioinformatics algorithmic development will
become more valuable and reach a wider userbase.

**Comment by michaelbarton** [comment]
Thanks, I have updated my original comment with your text.

**Comment by leipzig** [comment]
One thing I think that Docker in general and Bioboxes in particular can address is accelerating the "edit cycle" of research. Typically you develop an analysis that takes in a certain set of data and parameters and produces a report, and the principal investigator invariably wants to adjust explore the parameter space. So at that point you are beholden to either develop a full-scale web app to enable this or manually generate many iterations of reports yourself.

With a fully reproducible and portable analysis it should be possible to more easily build predictable interfaces that allow JSON-based descriptors of allowable parameters and allow investigators to generate instances of reports as they wish.

**Comment by michaelbarton** [comment]
Thank you for you email @leipzig. The idea of having a defined set of
parameters that can be iterated over to provide a better result is a good idea.
I have received a similar question related to @nucleotides, for example could
an assembler container provide a variable where the kmer value can be specified
by the user and so altered and iterated over a range of values.

I have thought about this a few times and my current answer is that we should
try to push this kind of analysis inside the container and automate it as much
as possible. For instance using assembly, tools like kmergenie by @rchikhi can
be bundled inside a container with the assembler, and then try to estimate the
best kmer. My ideal situation would an increase in these type tools so that one
day it would be less valuable to manually iterate parameters because the tools
have become sufficiently advanced to always do a better job than a person.

**Comment by michaelbarton** [comment]
I will close this issue for two reasons:

  * We have for the time being moved away from using version numbers to manage the project. Right now the interface seems relatively stable but possibly not version 1.0 since it has not been in wide spread use and testing.

  * Community adoption is an on going process and is not likely to be complete, at least in the short term.
