### ISSUE TITLE
Present bioboxes presented as a standard at BOSC 2015

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#52]
The [Bioinformatics Open Source Conference][bosc] 2015 will be a good
opportunity to spread awareness of bioboxes as a standard. To attend we will
have to submit and abstract by April 2015. @peterjc is an organising co-chair
and may be able to advise on how bioboxes could contribute. Perhaps a workshop
on how to use containers in bioinformatics or something similar?

[bosc]: http://www.open-bio.org/wiki/BOSC_2015

**Comment by peterjc** [comment]
Presenting BioBoxes as a talk (and poster?) would fit fine at BOSC. Assuming similar sections/themes to last year at least under *Bioinformatics Open Source Project Updates*, perhaps under *Open Science and Reproducible Research*. So please do submit an abstract.

I think it would also make sense to come to the CodeFest for more hands on interaction with interested parties?

**Comment by hlapp** [comment]
> I think it would also make sense to come to the CodeFest for more hands on interaction with interested parties?

:+1:

**Comment by michaelbarton** [comment]
Thanks for the suggest Peter. A session on bioinformatics containers at the
codefest is a good idea.

**Comment by michaelbarton** [comment]
Discussed in meeting #67. This issue is dependent on funding for the core team
to travel and stay in Dublin. @avilella will look into this.

**Comment by peterjc** [comment]
I've just added this to http://www.open-bio.org/wiki/BOSC_Abstract_Submission (it was just on the actual submission form):

*If the registration fee would prevent you from attending BOSC, please let us know in the Comments box when submitting your abstract. We have a limited number of free and half-price spots for accepted speakers.*

**Comment by michaelbarton** [comment]
@avilella's company will not provide travel expenses for anyone from bioboxes
 to attend BOSC 2015. This means I cannot attend BOSC 2015 as the JGI will not
 provide travel expenses for me. In meeting #52 we discussed the option of
 @pbelmann possibly attending. This needs to be resolved soon otherwise the
 abstract deadline will pass.

**Comment by michaelbarton** [comment]
@pbelmann Presented a poster and a talk at BOSC 2015 I heard his talk was received very well. Great work Peter.

**Comment by peterjc** [comment]
@pbelmann we (BOSC) will be in touch by email, but if you want to can already upload your slides and poster to the BOSC F1000 Research Channel here http://f1000research.com/channels/BOSC (open access, no charge). We'll be adding links to the schedule page as well: http://www.open-bio.org/wiki/BOSC_2015_Schedule

**Comment by pbelmann** [comment]
@peterjc  Yes, I will upload the talk and the poster. Thank you for accepting our abstract. I enjoyed the conference and I hope that I can attend BOSC 2016.

**Comment by peterjc** [comment]
Great! Thank you for submitting & presenting! Fingers crossed for BOSC 2016 :)
