### ISSUE TITLE
Binning and Profiling formats

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#55]
I think we should somehow mention cami in the binning and profiling format definitions because it was originally designed by the cami team with the aim to standardize the binning/profiling format and make the life of a developer who works with binning or profiling easier.
Thats why I suggest to rename the binning and profiling formats to cami_binning and cami_profiling or something similiar.

What do you think?

**Comment by michaelbarton** [comment]
Closed in favor of #68
