### ISSUE TITLE
Link to Generic bioinformatics container and Database section

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#60]
We should link the generic bioninformatics container and the database section from every container.

**Comment by michaelbarton** [comment]
I agree.

The fix for this will update each container RFC file and include a few lines
mentioning that each container should also follow the spec defined in the
generic bioinformatics container RFC.

**Comment by michaelbarton** [comment]
Discussed in meeting #67 and @pbelmann will look into this.
