### ISSUE TITLE
Create a base Docker image for validating containers

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#63]
Biobox images should be validated to ensure they are correct (#35). A base
image can be created using the [short-read assembler validator image][image] as
an example. This should be straightforward and only needs to the files in
/root/features/ to be removed. The base image should be hosted on the
`bioboxes/validator-base`.

[image]: https://github.com/bioboxes/validator-short-read-assember

**Comment by pbelmann** [comment]
@michaelbarton I have created a repository for a base image pbelmann/validator-base. When you give me the rights, so I can transfer the ownership to bioboxes, we can close this issue. You can also create an empty repo so I can push my code.

**Comment by michaelbarton** [comment]
I have created the bioboxes github repository for this. I've also set up the
bioboxes [docker repo][] for the image so this can be used as a base image.
I've set up [circleci][] to test the image to ensure it builds with any further
pull requests.

[docker]: https://registry.hub.docker.com/builds/github/bioboxes/validator-base/
[circleci]: https://circleci.com/gh/bioboxes/validator-base

**Comment by michaelbarton** [comment]
Thanks for creating this @pbelmann.
