### ISSUE TITLE
Create version file within RFC project

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#66]
This file should list the different versions of each RFCs by pointing to their
versions on github.

**Comment by michaelbarton** [comment]
Discussed in meeting #67. @fungs has implemented a README for the data-format
directory. He has agreed to do the same for the container directory. This file
will link to the major versions of each RFC in the github repo.

**Comment by pbelmann** [comment]
Thank you @fungs and @michaelbarton,  we now have version files for the file formats

https://github.com/bioboxes/rfc/tree/master/data-format

and for the containers:

https://github.com/bioboxes/rfc/tree/master/container 

I will add a link for the new assembler spec and close this issue.
