### ISSUE TITLE
Biweekly review meeting - Thu Mar 12 15:30 GMT

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#67]
### Agenda from previous meeting

  * Bioboxes validator base image (#63)
  * Create bioboxes website (#16).

Please add other items to the agenda using this ticket.

**Comment by michaelbarton** [comment]
@Leprevost would you be able to attend this meeting? If possible I would like
to assign issues to everyone in the @bioboxes/core-team.

**Comment by michaelbarton** [comment]
I think we should discuss #61 - managing configuration for containers in
general.

**Comment by fungs** [comment]
If it isn't a general problem with anyone in a particular time zone, could we prepone the following biweekly meetings by an hour, otherwise meetings might end like 19:00 CET like last time, which is kind of late.

**Comment by avilella** [comment]
Find by me - @avilella - GMT

**Comment by Leprevost** [comment]
Yes I think I will be available. There is a small chance that I will not be on-line because of my moving, but I will do my best to participate.

**Comment by mr-c** [comment]
Where is this meeting held?

**Comment by avilella** [comment]
So far it's been a skype conf call. @michaelbarton adds people to the call,
so he probably will need your skype id.

**Comment by Leprevost** [comment]
my Skype name is leprevostfv

**Comment by michaelbarton** [comment]
That's good for me too, I've moved the time an hour earlier.

**Comment by michaelbarton** [comment]
I propose the @bioboxes/core-team spend the first 30 minutes of the meeting
going through the issues and assigning them. For the last 30 minutes @mr-c
could the call and talk about about CWL language if he is willing.

@Leprevost you are welcome to join that the latter half of the meeting. If you
would to take some issues to work on, then you should join us for the first 30
minutes too.

**Comment by Leprevost** [comment]
Thanks @michaelbarton , I will try to get the meeting from the beginning.

**Comment by michaelbarton** [comment]
@mr-c If possible, you are welcome to join our meeting at 16:00 GMT. Could you give me your skype name if you would like to join us.

**Comment by Leprevost** [comment]
I apologize but I will not be able to participate the meeting, I have to deal with some urgent issues today.

**Comment by avilella** [comment]
@tetron (Peter A.) may join. 

For the next conf call in two weeks time (@michaelbarton, can you open an issue) I suggest we can talk about arvados and their crunch scripts, to see an example of how to consume bioboxes containers in real life.

**Comment by tetron** [comment]
Hi @avilella, my Skype name is peter.i.amstutz

**Comment by michaelbarton** [comment]
### Attending

  * Albert Vilella (@avilella)
  * Andreas Bremges (@abremges)
  * Johannes Dröge (@fungs)
  * Michael Barton (@michaelbarton)
  * Peter Belmann (@pbelmann)

### Reviewed Issues

  * #9 Type signatures are still a relevant discussion and are related to #86
    and #61. This issue will remain open.

  * #15 Different compression formats will be useful since gz is outdated.
    There are however greater priorities in the short-term. This issue will be
    closed.

  * #35 Biobox validators are still a priority. These will be created once we
    have settled on a specification for passing data (#61, #86).

  * #39 @avilella has been looking into creating a non-profit charity. A
    charity doesn't need to be registered if there is less than £15,000, and
    the donors do not need tax receipts.

  * #44 We currently have a group of contributors meeting once every two weeks.
    This issue will be closed and can be revisited if necessary.

  * #45 An editorial, as discussed in #47 with @ScottBGI, will provide exposure
    for bioboxes to the bioinformatics community. We will should be completed
    before BOSC 2015 (#65). The timelines we agreed were an initial draft by
    May 1, and to submit by June 1.

  * #46 Instructions for editors and reviews are dependent on agreement of a
    specification (#61, #85) and working validators (#35).

  * #47 Adoption of bioboxes standards by journals will become a greater
    priority once we have editor/reviewer instructions (#46) and working
    validators (#35).

  * #48 Creating a community standard is dependent on all other current
    outstanding issues.

  * #52 The bioboxes team will aim to attend BOSC 2015. The issue will be if
    everyone can get funding for travel expenses. @avilella will talk to the
    purchasing department at his company about this.

  * #60 @pbelmann will take this issue.

  * #61 This issue has received many comments in the last week and is a
    priority for the CAMI members of the team as they would like to link to a
    set of instructions for creating an assembler biobox. @pbelmann will
    propose an updated specification for passing data. We will aim to get this
    resolved by the start of next week.

  * #65 Not a current priority. The abstract deadline is April 3rd, and so
    should be a priority at the next meeting.

  * #66 @fungs has created a file listing the previous data format RFCs. He
    will also do the same for for the container RFCs.

  * #69 We discussed the issue of passing a database listing to a container but
    could not reach an immediate consensus. @fungs has a possible solution and
    will comment further on the issue.

  * #70 @leprevost has mentioned in the ticket he is interested in
    participating the development of bioboxes. This issue will be closed.

### Common Workflow language

@tetron joined our conference call for the second half. He described the
details and motivation behind the CWL which shares overlap with bioboxes. After
discussion we agree to continue to follow communication between the two
projects. A first step was to share the bioboxes method for passing data to a
container (#61) once we have agreed on this ourselves. We can then continue
discussion using this as a concrete example.

### New Issues

  * #87 Plan the gigascience editorial (#45).
  * #88 Use IRC for more informal discussions and questions
  * #89 Next meeting March 26

### Next Targets

  * Use google hangouts instead of skype for the next meeting.
  * Use irc chat room for intermediate questions and discussions.
  * Finalise usable input/output specification so that containers can start
    being implemented for CAMI.
