### ISSUE TITLE
Bioboxes account at Docker Hub

### ISSUE THREAD

**Issue by Leprevost** [bioboxes/rfc#78]
One of the features docker provides is the ability to search and download pre-build images. To make bioboxes images available, we need to create an [account](http://hub.docker.com) (they have organization accounts too).

The Hub has an integrated build system where you point a Github repository as being the source of the image, then the Hub pulls the repository and builds it. Hooks can also be reconfigured so every time the repository is updated, so does the image.

I think this is important because it will allow people to download "official" and reviewed images, instead of building them every time.

**Comment by avilella** [comment]
Do you mean an org account on docker or on github?

Very good point about the hooks. Is there a page with examples or
documentation to see how this is done? It would be great to have the
github->docker webhooks, specially to test that changes in the
bioinformatics app don't affect the container.

Regarding the accounts, on docker, I know there is a "nucleotides" one
already there with some containers in it, not sure if it's personal or org
account.

@michaelbarton, shall we rename the nucleotides docker account, create a
new one, do something else?

**Comment by Leprevost** [comment]
I mean on docker Hub (it is also called docker registry).

I don't remember to follow any documentation, I learned how to use on my own. The process is pretty straightforward, you only have to create an Automated Build repository (at docker hub), and the website will ask you where the Github repository is and if you wish to make it automatic updates. You can check the hexabio account at docker hub for some examples, all my repos there are automatic builds.

I can create some sort of tutorial if needed.

**Comment by avilella** [comment]
It would be great if you give it a go: I am thinking it would be either the
URL of an existing tutorial or write a small one in our github, so that
other people less familiar with it (like me) can go through the document :-)

**Comment by Leprevost** [comment]
I found this at docker hub website, it explains on how to use automatic builds: http://docs.docker.com/docker-hub/builds/

**Comment by michaelbarton** [comment]
This is a good suggestion. I've created a dockerhub organisation for bioboxes.
If you give me your dockerhub names I will add you to this.
