### ISSUE TITLE
Write a call-for-contributions commentary article for gigascience.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#87]
We will publish an commentary in GigaScience (discussed in #45 and #47). This
editorial will be a call for feedback and implementations of bioboxes. The word
limit for the editorial is 1200 words. The first step is to plan the outline of
this article.

The resolution of this issue should be a text plan as a bioboxes github repo.
Once this is created, other members of @bioboxes/core-team should provide
feedback through PRs until we reach consensus.

**Comment by abremges** [comment]
Instructions for authors (an editorial is the second form listed AFAIK):
http://www.gigasciencejournal.com/authors/instructions/commentary

**Comment by ScottBGI** [comment]
FYI, unless we as the editors wrote this ourselves we'd probably take this as a commentary rather than editorial. Its essentially the same type of article though, and the word count and instructions for authors @abremges has posted are correct. The other thing to watch out for is it has to have 10 or less references. You can see a few examples of similar "call to arms"/project announcement papers here:

http://www.gigasciencejournal.com/content/2/1/2
http://www.gigasciencejournal.com/content/1/1/5 (this one was too long so we counted it as a short review instead)

If you want any feedback before you submit feel free to pass a draft to me. Looking forward to seeing the results soon!

**Comment by Leprevost** [comment]
sorry if this is offtopic, but I think it may interest everyone;  just saw this today:
http://arxiv.org/abs/1410.0846

**Comment by asczyrba** [comment]
this is actually published already

http://dl.acm.org/citation.cfm?id=2723882 <http://dl.acm.org/citation.cfm?id=2723882>

**Comment by avilella** [comment]
I think we have Carl Boettiger in the list of stakeholders for bioboxes,
haven't we?

@michaelbarton , did we contact him?

**Comment by avilella** [comment]
I emailed Carl just now. Let's see if he gets back to us.

**Comment by ypriverol** [comment]
@Leprevost Both examples are fine but they are more like introduction to Docker. I read both of them and they basically propouse the idea of reproduce science using docker, but this idea is not new, some other references before propose the idea of store the machines that were used for the bioinfo analysis (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285). 

@michaelbarton I don't know how feasible could be to write this manuscript on Bioinformatics or in Plos Computational Biology. But is just an idea

**Comment by avilella** [comment]
Thanks @ypriverol .

Let me just briefly summarise where we are now, and please
everybody/anybody correct me if I am wrong. I think there are two stages
here:

One is the short editorial/comment publication, which is this github ticket
#87, and it seems gigascience are keen on us publishing there.

Then there is something bigger, which is the first draft of the
specification, which in Summer time we will present at BOSC, and just after
BOSC, given the feedback from the community at large, we will turn into a
manuscript (similar to MIAME or MIAPE), and submit to a scientific journal.

Cheers

**Comment by ypriverol** [comment]
@avilella thanks for clarification.

**Comment by michaelbarton** [comment]
Thanks for the clarification @ScottBGI. I've updated the issue title to reflect this is a commentary.

**Comment by michaelbarton** [comment]
I've created a repository for the article here - https://github.com/bioboxes/commentary-article

I encourage anyone to who would like to start planning this article to go ahead and submit a pull request. The BOSC 2015 abstract deadline is approaching so I will also ask that someone consider taking a look at this issue too - #65

**Comment by michaelbarton** [comment]
@ypriverol What @avilella wrote is correct. I think we've agreed that a larger second article be written when the standard is more mature and we are seeing bioboxes being regularly used.

**Comment by michaelbarton** [comment]
I have written an initial draft of this article.

https://github.com/bioboxes/commentary-article/tree/initial-draft

**Comment by michaelbarton** [comment]
@bioboxes/core-team @ScottBGI I have written an initial draft within the 1200 word limit. What do you think?

https://github.com/bioboxes/commentary-article

**Comment by abremges** [comment]
Great starting point (and more), @michaelbarton 

1. As bioboxes gained some momentum by now, I believe we should include *bioboxes* in in the title.
1. You motivate bioboxes in much detail, but ignore its history (joining forces between your nucleotid.es and our CAMI initiatives). I think this should be included, as without either of these bioboxes would not exist.
1. I'd emphasize the work done within the bioboxes initiative a bit more (i.e. which bbx standards are there already, how many bbx implementations do we have ready to use)
1. Make the call to action more concrete: Ask developers to actively form the bioboxes standards, and package their tools as bioboxes.

Let me know if you want me to get actively involved, or if this is reserved to the @bioboxes/core-team

**Comment by michaelbarton** [comment]
I've updated the issue title to reflect this more than a discussion of the outline. I closed related issue #45 in favor of this one.

**Comment by ScottBGI** [comment]
Looks a good start, but agree with @abremges points, especially the need for an explicit call for action - as this is sort of the point of the announcement paper. Plugging the website, GitHub, RFC could be useful, plus you could even link out to some interactive examples. Can probably squeeze in another few hundred words, but the 10 reference limit is more fixed (including URLs). You can also fit more in if you include figures or links to dockerised examples. Your Balti & Bioinformatics talk had lots of nice graphics, and if there was ways to explain the rationale with flow diagrams or infographics that is all bonus wordcount.

**Comment by michaelbarton** [comment]
@rvosa opened an issue on the commentary article, I will paste his comment here as it is related to the discussion.

> I think the bioboxes initiative is great. At Naturalis we are developing applications that are just complicated enough to be a huge hassle for users to install, so for now we are opting for (Vagrant-managed) virtual machines.

> However, VMs have a big overhead so we are planning to move to docker containers. I strongly agree that a bit of sensible community planning to adopt bioboxes would be a great boon, and so we are planning to make such a move (e.g. naturalis/supersmart#52).

> As a watcher of bioboxes on github I noticed you have started a commentary article. I am curious about your intentions with this. Presumably you are looking for community "buy in". Does that also mean that this commentary article is intended to be collaborative with a whole bunch of people signing off on this? I.e. can I help?

**Comment by rvosa** [comment]
Yup, that was me. I've been watching bioboxes on the sidelines for a while now because I think it's such a good initiative and something that we would like to adopt. I basically had the same question as @abremges, i.e.:

> Let me know if you want me to get actively involved, or if this is reserved to the @bioboxes/core-team

**Comment by michaelbarton** [comment]
> Let me know if you want me to get actively involved, or if this is
  reserved to the @bioboxes/core-team

The article is open to everyone. We would like bioboxes to be a community
effort and so we welcome suggestions and pull requests.

**Comment by michaelbarton** [comment]
> Does that also mean that this commentary article is intended to be
  collaborative with a whole bunch of people signing off on this? I.e. can I
  help?

Yes if you have any suggestions or improvements, I would be happy to see them.

**Comment by michaelbarton** [comment]
> Looks a good start, but agree with @abremges points, especially the need for
> an explicit call for action - as this is sort of the point of the
> announcement paper.

Agreed.

> Plugging the website, GitHub, RFC could be useful, plus you could even link
> out to some interactive examples.

Agreed.

> Can probably squeeze in another few hundred words, but the 10 reference limit
> is more fixed (including URLs).

A few more words would definitely be useful as I cut a few paragraphs from my
original draft to reach the limit.

> You can also fit more in if you include figures or links to dockerised
> examples. Your Balti & Bioinformatics talk had lots of nice graphics, and if
> there was ways to explain the rationale with flow diagrams or infographics
> that is all bonus wordcount.

This is a good idea that I had not thought of. In his BOSC 2015 talk, @pbelmann
created a figure to describe bioboxes. It would be good to build upon this for
developing an infographic description of what bioboxes is. This would be useful
for future talks etc..

**Comment by michaelbarton** [comment]
> As bioboxes gained some momentum by now, I believe we should include
  *bioboxes* in in the title.

Agreed

> You motivate bioboxes in much detail, but ignore its history (joining forces
  between your nucleotid.es and our CAMI initiatives). I think this should be
  included, as without either of these bioboxes would not exist.

Agreed, it may also be worth mentioning that a common format for benchmarking
makes benchmarks more worthwhile because the same images are tested and shared
across benchmarks.

> I'd emphasize the work done within the bioboxes initiative a bit more (i.e.
  which bbx standards are there already, how many bbx implementations do we
  have ready to use)

Could you expand on this point more?

> Make the call to action more concrete: Ask developers to actively form the
  bioboxes standards, and package their tools as bioboxes.

Agreed.

**Comment by michaelbarton** [comment]
Summary of the feedback so far:

  * Add a call to action from developers. Ask for them to contribute images and
    provide feedback on the existing specifications.

  * Add links to website and RFC.

  * Update title to include "bioboxes". The character limit is 80, so specific
    suggestions are welcome.

  * Mention that the history of bioboxes comes from CAMI and nucleotid.es.

  * Include a graphic which helps explain the concept #168.

  * Include working examples that people can try.

**Comment by rvosa** [comment]
I think the commentary article might also make the point that there is great interest (also, e.g., among computer scientists) in tracking provenance and ensure reproducibility of research outcomes. Having explicitly versioned, fully specified analytical environments helps.

**Comment by michaelbarton** [comment]
>  tracking provenance and ensure reproducibility of research outcomes.
>  Having explicitly versioned, fully specified analytical environments
>  helps.

Could you expand on this point further? How might I include it in the
existing article? Some example text would be even better if you have the
time.

**Comment by rvosa** [comment]
I guess my basic point was that the provenance of bioinformatics research results is often hard to reconstruct or reproduce: often times, some paper gets published with significant results, but others trying to replicate the study don't arrive at the same results. 

One of the factors that contributes to this is that people don't explicitly record which exact version of what tool they used (not to mention all the turtles that are stacked underneath that tool in terms of OS libraries, bit depth, and so on). 

If we dockerize our tools, then some of the ambiguity with respect to the turtles that are stacked underneath the tools that we use is removed. Hence, this should contribute to reproducibility, more or less along the lines of Rule 3 in this paper: http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285 (note also the studies that are cited in the introduction of that paper, which substantiate my point about this "crisis" in reproducibility).

Today is unfortunately my last day before I go on vacation so right now I can't really contribute text to the article. Once I'm back (3 weeks from now) I'd be able to contribute. Last time I contributed to a manuscript on github, the approach we took was to fork the ms, make lots of little edits and commits, then send a pull request. This gives you the option of deciding quite granularly what you want to merge back in. Would that work for you?

**Comment by michaelbarton** [comment]
Additional changes on this github branch - https://github.com/bioboxes/commentary-article/tree/second-draft

**Comment by michaelbarton** [comment]
![poster](https://cloud.githubusercontent.com/assets/1142/8857603/8a3f68be-316a-11e5-8fa5-71f74d7bafad.png)
Here's an initial draft of the figure for commentary. Any feedback or improvements are welcome, the eps file is on the 'second-draft' git repository.

**Comment by michaelbarton** [comment]
I have revised and updated the article. I will aim to submit this by the end of
the week. The latest version is the master branch if there are further
suggestions and feedback.

**Comment by Leprevost** [comment]
hey Michael, I just forked the repo. I was thinking about adding a small paragraph to talk about possible problems or issues about the idea of using containers, like license infringements for example. I will go on the paper and ass some points if you don't, mind. Feel free to accept/reject them.

**Comment by michaelbarton** [comment]
Thank you for your PR @Leprevost. I have a few comments:

  * I think it's good that you hightlighted this shouldn't just be a genomics
    focused article and include all of the bioinformatics community.

  * The article has a word limit of ~1200, although Scott mentioned we could
    include a couple more hundred. I think the additional paragraphs you added
    push this upwards of 1600. I think licensing is important to mention, could
    you reduce this to a sentence or two?

  * Reproducibility is mentioned earlier in the article, is this similar to
    what you intended to include?

**Comment by Leprevost** [comment]
That is OK, I presumed that the article was on its limit. I will re
organize that licensing phrase and remove the reproducibility part.

**Comment by michaelbarton** [comment]
@Leprevost thanks that would be useful.

**Comment by michaelbarton** [comment]
Thanks for the PR by @fungs, @pbelmann and @abremges. I have merged these
together and updated the main document. I will submit this on Friday. Please
take a look, all authors need to approve the document before I submit it. Minor
fixes are welcome but I don't want to make anymore large changes.

**Comment by abremges** [comment]
Thanks, @michaelbarton - I really like the manuscript as it is now. Will re-read it one last time, extra-carefully, before we submit.

FYI, Bielefeld University can cover all publication costs through their institutional BMC account if e.g. @pbelmann handles the submission process (and we add one sentence to the acknowledgements section).

**Comment by abremges** [comment]
>> I'd emphasize the work done within the bioboxes initiative a bit more (i.e.
which bbx standards are there already, how many bbx implementations do we
have ready to use)

> Could you expand on this point more?

So far, we have bbx specs for assembly, binning, and profiling tools. We mention the assemblers in the article (plus read mapping, for which we do not have a spec, yet), but ignore binning and profiling.

We might even go one step further, and explicitly list how many bbx implementations we currently have (e.g. how many assemblers did we implement), but this of course this info will be outdated very soon. *Something to list on the website in my opinion.*

**Comment by abremges** [comment]
**I just talked to @alicemchardy, she read and approved the article.**

**Comment by michaelbarton** [comment]
![poster](https://cloud.githubusercontent.com/assets/1142/9074223/862f0cf6-3abc-11e5-8da6-0917469df133.png)

Attached is the updated figure.

**Comment by michaelbarton** [comment]
Thanks for the suggestions and edits everyone. I've integrated all of the these
and proof read it once more. I have also updated the figure, including @fungs
suggestions.

If everyone is satisfied, I will submit this.

**Comment by fungs** [comment]
@Leprevost If not for the commentary I would welcome details about the differences/limitations using containers on the bioboxes website. This would also inform users before they run into problems building bioboxes.

**Comment by michaelbarton** [comment]
I have submitted the manuscript to gigascience. Thank you to everyone who
participated. I read through the article once more before submitting it and I
felt that everyone's constructive feedback has created an article much, much
better than my original draft.

Publications are important for building an academic CV, and if we continue
working on improving bioboxes and it's adoption in the bioinformatics
community, I think this will not be the last article we produce together.

**Comment by michaelbarton** [comment]
I've received the copy editor changes from gigascience and integrated them into
the article. These are mainly just minor changes except where Figure 2 is now
Box 1. These changes are in the latest version of the master branch. As these
changes are limited I will submit on Monday unless there any problems.

**Comment by abremges** [comment]
Thank you, @michaelbarton. I've created https://github.com/bioboxes/commentary-article/pull/17 with some minor enhancements. Other than that, looking great & ready for re-submission!

**Comment by michaelbarton** [comment]
I received notification this morning that the article  has gone to production.

**Comment by abremges** [comment]
Awesome, thanks & congratulations!

**Comment by michaelbarton** [comment]
I received the article proofs today so hopefully it should appear in press soon.

**Comment by accopeland** [comment]
Any idea what 's up with cami ?

On Fri, Oct 2, 2015 at 6:55 PM, Michael Barton <notifications@github.com>
wrote:

> I received the article proofs today so hopefully it should appear in press
> soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioboxes/rfc/issues/87#issuecomment-145193042>.
>



-- 

Alex Copeland
Joint Genome Institute, Walnut Creek, CA 94598

**Comment by abremges** [comment]
Finally, thanks @michaelbarton! Took quite a while, nice to see progress.

@accopeland We're on it! In depth evaluations take time and effort...
If you want to help/get involved, please get in touch with @asczyrba.

**Comment by accopeland** [comment]
Yes, of course, no criticism intended.

On Sat, Oct 3, 2015 at 2:19 PM, Andreas Bremges <notifications@github.com>
wrote:

> Finally, thanks @michaelbarton <https://github.com/michaelbarton>! Took
> quite a while, nice to see progress.
>
> @accopeland <https://github.com/accopeland> We're on it! In depth
> evaluations take time and effort...
> If you want to help/get involved, please get in touch with @asczyrba
> <https://github.com/asczyrba>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioboxes/rfc/issues/87#issuecomment-145291697>.
>



-- 

Alex Copeland
Joint Genome Institute, Walnut Creek, CA 94598

**Comment by abremges** [comment]
Don't worry, no offense taken -- we also wish we had more to show by now, and are aware of the community's curiosity. At least for the assembly part, we plan to make first results available soon!
