### ISSUE TITLE
Can bioboxes use IRC for informal discussion and questions

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#88]
In meeting #67 I suggested that we might use IRC as an informal method for
discussions and asking questions. This was agreed as possibly being useful. I
have created [an IRC room on irccloud][room]. The advantage of ircclound is
that the channel will still remain after leaving and rejoining.

The resolution of this issue is whether or not IRC is useful for bioboxes
discussions.

[room]: https://www.irccloud.com/#!/irc.irccloud.com:6667/%23bioboxes

**Comment by avilella** [comment]
Can you give the details to login? thx

**Comment by michaelbarton** [comment]
@avilella you need an account on ircclound I think, and then should be able to access the room.

**Comment by avilella** [comment]
Got one now. what network/url ?

**Comment by michaelbarton** [comment]
irc.irccloud.com:6667

**Comment by michaelbarton** [comment]
Channel bioboxes

**Comment by pditommaso** [comment]
Did you take in consideration a [Gitter](https://gitter.im) chat?

It works pretty well and integrates smoothly with Github.

**Comment by michaelbarton** [comment]
@pditommaso No I hadn't. It looks interesting. Have you been using it? How does it fit into your workflow?

**Comment by pditommaso** [comment]
Yes, I'm using for Nextflow project. It provide unlimited history, markdown formatting and above all you can mention Github issues and pull requests. 

Have a look here https://gitter.zendesk.com/hc/en-us/articles/200176692-Issue-and-Pull-Request-mentions

**Comment by michaelbarton** [comment]
That's interesting, the pull requests and issue integration would be useful for discussing them in chat. What does everyone else in @bioboxes/members think?

**Comment by abremges** [comment]
I'd prefer Gitter over IRC.

This maybe removes some clutter from the Issues section.
Summaries of discussions should be posted in here, though.

**Comment by pbelmann** [comment]
+1 for Gitter

**Comment by fungs** [comment]
+1 Gitter

If we move to hangout for conference calls, this also gives us a chat. I'd go for the most convenient solution and GitHub integration sounds like just what we want.

**Comment by avilella** [comment]
The ADAM people also use Gitter:


   - Chat with ADAM developers at https://gitter.im/bigdatagenomics/adam

**Comment by michaelbarton** [comment]
OK, gitter is the consensus.

**Comment by pbelmann** [comment]
Thanks @michaelbarton for creating the gitter chat room. @bioboxes/members can join now. Go to https://gitter.im/bioboxes and sign up with your github account.

**Comment by pditommaso** [comment]
I hope there will be a "rfc" public room so also non members could join the discussion.

**Comment by pbelmann** [comment]
@pditommaso I agree. We should think about making the current room public or creating a second public room, so we can for example help non members creating or using bioboxes. But maybe not now because we are working on main parts of the spec.

**Comment by avilella** [comment]
I suggest we give ourselves some time for a final push on the spec and then
use the irc and github as channels to gather feedback from anyone
interested in the work that has been taking place.

**Comment by michaelbarton** [comment]
Yes a public room is a good idea. I didn't realize this was restricted.

**Comment by michaelbarton** [comment]
We will use the gitter room bioboxes/rfc for discussions.
