### ISSUE TITLE
Biweekly review meeting - Thu Mar 26 15:30 GMT

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#89]
We should discuss #65 as the BOSC 2015 abstract deadline is approaching. This
meeting will also be a google hangout. Please email me your gmail addresses.

**Comment by avilella** [comment]
@cboettig from rocker fame may join the google hangouts in the last 30-20 minutes of the call.

**Comment by ypriverol** [comment]
@avilella @michaelbarton Can I joint you in this meeting.

**Comment by avilella** [comment]
Cool, thanks @ypriverol .

@michaelbarton , just to summarise for you: @ypriverol and myself had
coffee this weekend in Cambridge UK, where I gave a (good?) lengthy
description of what bioboxes has been so far to @ypriverol . We will
hopefully see @ypriverol going through the current documents in here, and
in general participating in the project.

Cheers,

A.

**Comment by ypriverol** [comment]
@avilella Can you point me to the proper issues and documentation before start the discussion about #biodocker movements.

**Comment by avilella** [comment]
One could probably start with #86 #90 and #61 , but there are many others which also contain useful info.

**Comment by michaelbarton** [comment]
I've just updated the bioboxes website - there are now pages for [getting started][start] and [making contributions][contr].

[start]: http://bioboxes.org/getting-started/
[contr]: http://bioboxes.org/contribute/

**Comment by michaelbarton** [comment]
@ypriverol You can join the meeting. Are you interested in being assigned some issues?

I've added details about the organisation to the bioboxes website - http://bioboxes.org/organisation/

**Comment by ypriverol** [comment]
@michaelbarton more than happy to take an issue. Let me know how to start!!

**Comment by abremges** [comment]
I won't join the hangout tomorrow, it's my daughter's birthday.
@pbelmann and I will discuss open issues earlier. Thanks! /A

**Comment by fungs** [comment]
Sorry for the notification on such a short notice but I will be traveling today and I haven’t found a way to forward hangout calls to my phone.

**Comment by ypriverol** [comment]
Can I joint to the meeting @michaelbarton @avilella ?

**Comment by avilella** [comment]
@michaelbarton , do you want to postpone to another day so that we have
more quorum?

I can do 15:30 GMT today. I am fine either way :-)

**Comment by avilella** [comment]
My gmail account is 'avilella' at gmail.com

**Comment by michaelbarton** [comment]
I'll start a hangout now.

**Comment by michaelbarton** [comment]
Here the [hangout][]

[hangout]: https://plus.google.com/hangouts/_/gq3q6tue52f4eslddlmqafeuhua

**Comment by michaelbarton** [comment]
@ypriverol you are welcome to join.

**Comment by michaelbarton** [comment]
### Attending

  * Albert Vilella (@avilella)
  * Michael Barton (@michaelbarton)
  * Peter Belmann (@pbelmann)
  * Yasset Perez-Riverol (@ypriverol)

### Reviewed Issues

  * #86 The isse of passing and validating the input data to the biobox is the
    current top priority. This issues appears to be nearing completion as we
    will use [json schema][js] to validate the file given by the user to the
    biobox. The tool [input-validator][valid] can be used by biobox authors to
    do this, however this needs more documentation (#104).

  * #52 @avilella's company will not provide travel expenses for anyone to
    attend BOSC 2015. Therefore @michaelbarton will not be able to attend BOSC
    2015. We discussed the option of @pbelmann giving the presentation if he
    can attend.

[js]: http://json-schema.org/
[valid]: https://github.com/bioboxes/input-validator

### New Issues

  * #102 The input validator should have more documentation.

  * #103 The biobox schemas should be available for download.

  * #104 How can we manage different versions of the same biobox? @ypriverol
    brough this up as an issue. We could not find a simple solution during the
    meeting.

### Next meeting

The next meeting is set for two weeks #105. In between now and the next meeting
we will aim to start creating short-read assembler bioboxes, and then address
any issues related this next time.
