### ISSUE TITLE
Proposal: Standardised bioinformatics objects and morphisms

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#9]

**Comment by fungs** [comment]
Before reinventing the wheel we should realize that passing data and arguments is a form of interprocess communication and that there are many solutions around that will help to select the best possible one. From my point of view, we have to find out how to best fit a structured approach using JSON or similar in the container framework and how to define it in a way which leaves it open to other or new containerization techniques and other platforms.

Maybe we should have a look at how web services and pipelining tools are currently doing this although this is in a slightly different context. I'd suggest to start by looking at taverna and its modules. Maybe we could even aim for network transparency, making every biobox a possible web application.

**Comment by avilella** [comment]
This probably has some overlap with the efforts of the Global Alliance
project called common workflow language. I found the github URL the other
day:

https://github.com/common-workflow-language/common-workflow-language

Here are some more notes on the project:

        - Common Workflow Language working group

        - The Common Workflow Language (CWL) is an informal,
          multi-vendor working group consisting of various
          organizations and individuals that have an interest in
          portability of data analysis workflows.  Our goal is to
          create specifications that enable data scientists to
          describe analysis tools and workflows that are powerful,
          easy to use, portable, and support reproducibility.  CWL can
          be used to describe workflows for a variety of problem areas
          including data-intensive science like bioinformatics,
          physics, and astronomy; and business analytics such as log
          analysis, data mining, and ETL.

        - https://groups.google.com/forum/#!forum/common-workflow-language

        -
https://github.com/common-workflow-language/common-workflow-language

        - The Global Alliance for Genomics Health (GA4GH) is an
          "international coalition, dedicated to improving human
          health by maximizing the potential of genomic medicine
          through effective and responsible data sharing." The GA4GH
          is in the process of starting up a working group on
          workflows and containers and this working group will likely
          pick up and adopt the efforts of the Common Workflow
          Language group and its efforts of to create standard, modern
          formats for describing tools and workflows for
          bioinformatics platforms. Implementing support for these
          formats in Galaxy would allow tool and workflow authors to
          produce artifacts that could be shared across Galaxy, Seven
          Bridges, and Arvados and potentially other platforms in the
          future such as Mobyle.

**Comment by pbelmann** [comment]
I think this should be a topic in the next meeting.

**Comment by avilella** [comment]
CWL mentiones taverna et al:
https://groups.google.com/forum/#!topic/common-workflow-language/eGrNfpjuq2E

**Comment by avilella** [comment]
a mention to an already working cwltool for docker:

https://groups.google.com/forum/#!topic/common-workflow-language/A0JffijHipY

**Comment by michaelbarton** [comment]
This topic was reviewed in meeting #67. Type signatures are still relevant and
are being discussed in issues #86 and #61.

**Comment by michaelbarton** [comment]
This issue is being considered as part of definining how data is passed to a
biobox. A more concrete example

**Comment by michaelbarton** [comment]
We have implemented signatures for the biobox RFCs. For example we have
specified that the every short read assembler should provide the signature:

    f : [fastq A], [Maybe insert_size A] → contigs B, scaffold C

This is indicates a biobox that takes a list of fastq files and a list of
optional insert sizes. They both have the algebraic type A, indicating that
that the entries correspond. E.g. for each fastq there maybe a corresponding
insert size entry in the second list.

I think these should be the central method for describing what a biobox does
because I think it contains all the information required in a succinct format.
I believe we could also overlay a type system once we chain containers
together, for instance if we build a workflow that uses the output of container
A as the input for container B, it would be possible to check that the
signatures match before executing the workflow. This would prevent the kinds of
errors where a workflow breaks halfway through because of incompatible data
types.

My thought on the `biobox.yml` file is that it is a way of providing input,
where the format of the data should match the signature of the biobox. If the
formats do not match the biobox should not be run.

**Comment by michaelbarton** [comment]
I will close this as I believe the signature formats in the RFCs implement this.
