### ISSUE TITLE
New short-read genome assembler container spec

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#95]
@michaelbarton I created a branch  with the draft for the new assembler spec. We should merge this when issues #61 and #90 are closed. For now I chose one of the definitions discussed in #61 as an example.
I think we can exchange the schema technology discussed in #86 later if we want to, so we don't have to wait for closing #86. 
Instead of using fasta as output type, we should think about using the CONTIG and SCAFFOLD types.

#### Still missing:
  * **Signatures**. At least one of the signatures the assembler has to support.
  * **EDAM**. This is my first impression of EDAM: For the new assembler spec we need the specification for FASTQ, CONTIG, SCAFFOLD, fragment size, paired end and single end.
         
    * FASTQ seems to be available as a FORMAT spec: [FASTQ-like format (text)](http://www.ebi.ac.uk/ontology-lookup/?termId=format%3A2182) and four different FASTQ child nodes like [FASTQ](http://www.ebi.ac.uk/ontology-lookup/?termId=format%3A1930) or [FASTQ-illumina](http://www.ebi.ac.uk/ontology-lookup/?termId=format%3A1931)  
    * CONTIG and SCAFFOLD could be expressed as a data type like [sequence-assembly](http://www.ebi.ac.uk/ontology-lookup/?termId=operation%3A0524). There is a [scaffolding](http://www.ebi.ac.uk/ontology-lookup/?termId=operation%3A3216) operation defined. 
    * I have not found anything for fragment size, paired end and single end.

          Maybe we should not try to define everything in EDAM.

Please comment and edit the the branch.

**Comment by michaelbarton** [comment]
Thanks @pbelmann. I had time to take a quick look at the branch containing the
updated RFC, this looks good. I suggest we try creating an assembler that
accepts these inputs? I know that you created the soap biobox, would this
already work with what we've described? I might guess that we need to something
for the signature acceptance part.

As for the EDAM, we could drop the requirement for this in short term if it
makes development easier. I don't know how much using EDAM terms would add
right now. Perhaps when we have different bioboxes communicating with each
other this might become more of an issue.

**Comment by pbelmann** [comment]
>Thanks @pbelmann. I had time to take a quick look at the branch containing the
>updated RFC, this looks good. I suggest we try creating an assembler that
>accepts these inputs? I know that you created the soap biobox, would this
>already work with what we've described? I might guess that we need to something
>for the signature acceptance part.

I would suggest to clarify #61, then I would continue to work on #90 and after that I or we could update the new assembler spec branch. I will add an example for a signature part, maybe you could take a look at it later.

>As for the EDAM, we could drop the requirement for this in short term if it
>makes development easier. I don't know how much using EDAM terms would add
>right now. Perhaps when we have different bioboxes communicating with each
>other this might become more of an issue.

I agree.

**Comment by avilella** [comment]
I also feel like EDAM shouldn't slow things down for now. It will probably
be relatively easy to add EDAM ids later on as an extra feature, so I say
let's keep EDAM on hold in the system and retake it as a task later on.

**Comment by pbelmann** [comment]
We have merged the new assembler spec, so I will close this issue. EDAM will be integrated in higher bioboxes versions.
