### ISSUE TITLE
compile a list of potential apps to box

### ISSUE THREAD

**Issue by avilella** [bioboxes/rfc#99]
I found this website which could be a good start:

http://omictools.com/

E.g. for assemblers:

http://omictools.com/genome-assemblers-c93-p1.html

(please mark as duplicate if this issue is covered elsewhere)

**Comment by Leprevost** [comment]
I think thats a good website to start. I'n also planning to migrate biodocker images to bioboxes

**Comment by pbelmann** [comment]
I would say we try to containerize the [nucleotid.es](https://github.com/nucleotides?page=1) assemblers (they are all listed on the omictools website) with our [new assembler specification](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd). 
I suggest we create an issue for every assembler in nucleotid.es and reference this issue (#99), so we have an overview of the progress.

**Comment by michaelbarton** [comment]
I agree with @pbelmann. The nucleotid.es images already contain the code to build the assembler. They will need converting to the existing bioboxes CLI. This was once of the original goals of this project so that we could use the containers interchangeably. I think we've made a lot of good progress to get here.

Once thing that might be necessary is to provide more examples or a guide on the website of how to build a biobox from scratch and how they work.

**Comment by michaelbarton** [comment]
@sjackman also has a Dockerfile with many assemblers installed. We could also use this too.

https://github.com/sjackman/docker-bio/blob/master/assemblers/Dockerfile

**Comment by sjackman** [comment]
I would definitely support using Linuxbrew and Homebrew-science to compile/install bioinformatics tools.

**Comment by pbelmann** [comment]
Ok then I will create the first issues now. I will suggest using linuxbrew or nucleotid.es assemblers for assembler bioboxes.

**Comment by michaelbarton** [comment]
@bioboxes/members The issues @pbelmann have created would be a great place to start if you are interested in contributing to bioboxes. We have some documentation on the sebsite and if you could give feedback as you make your box, or even better PR to improve the documentation, that would be very helpful.

**Comment by michaelbarton** [comment]
I will close this ticket as inactive.
